// Saltline sailing — polar tables at runtime (docs/SAILING-CONTRACT.md §2.11). Bilinear in polars.gen.js (generated by
// scripts/gen-polars.mjs from the steady-state solver in vpp.js). Pure, deterministic, cheap (no aero calls).
import { POLARS } from './polars.gen.js';
import { rigOf } from './rigs.js';

const ZERO = Object.freeze({ kn: 0, heel: 0, leeway: 0, level: 0 });
// index + fraction of x in a sorted axis (clamped to the ends)
function seg(ax, x) {
  const n = ax.length;
  if (!(x > ax[0])) return [0, 0];
  if (x >= ax[n - 1]) return [n - 2, 1];
  let i = 0; while (i < n - 2 && x > ax[i + 1]) i++;
  return [i, (x - ax[i]) / (ax[i + 1] - ax[i])];
}
const fold = (twa) => { const a = Math.abs((((Number(twa) || 0) % 360) + 540) % 360 - 180); return a; };

/** → { kn, heel (°, ≤ phiT), leeway (°), level } for true wind twsKn (kn) at true wind angle twaDeg (|twa| folded 0…180). */
export function polarSpeed(cls, twsKn, twaDeg) {
  const P = rigOf(cls) && POLARS[cls]; if (!P) return ZERO;
  const tws = Number.isFinite(twsKn) ? Math.max(0, twsKn) : 0, twa = fold(twaDeg);
  const [i, fi] = seg(P.tws, tws), [j, fj] = seg(P.twa, twa), nA = P.twa.length;
  const at = (arr, a, b) => arr[a * nA + b];
  const bil = (arr) => (1 - fi) * ((1 - fj) * at(arr, i, j) + fj * at(arr, i, j + 1)) + fi * ((1 - fj) * at(arr, i + 1, j) + fj * at(arr, i + 1, j + 1));
  const ii = fi < 0.5 ? i : i + 1, jj = fj < 0.5 ? j : j + 1;
  return { kn: Math.max(0, bil(P.kn) / 100), heel: Math.max(0, bil(P.heel) / 10), leeway: bil(P.lee) / 10, level: at(P.lv, ii, jj) };
}

const vmgCache = new Map();
/** Best VMG up- and downwind: scans TWA 0…90 / 90…180 at 1° on the interpolated table. */
export function bestVmg(cls, twsKn) {
  const tws = Math.round((Number.isFinite(twsKn) ? Math.max(0, twsKn) : 0) * 10) / 10;
  const key = `${cls}|${tws}`;
  let r = vmgCache.get(key);
  if (r) return r;
  const up = { twa: 45, kn: 0, vmg: 0 }, down = { twa: 150, kn: 0, vmg: 0 };
  for (let a = 0; a <= 180; a++) {
    const kn = polarSpeed(cls, tws, a).kn, v = kn * Math.cos((a * Math.PI) / 180);
    if (a <= 90 && v > up.vmg + 1e-9) { up.twa = a; up.kn = kn; up.vmg = v; }
    if (a >= 90 && -v > down.vmg + 1e-9) { down.twa = a; down.kn = kn; down.vmg = -v; }
  }
  r = { up, down };
  if (vmgCache.size > 4000) vmgCache.clear();
  vmgCache.set(key, r);
  return r;
}
/** The HUD no-go half-angle = best upwind VMG angle − 5. */
export function noGoDeg(cls, twsKn) { return bestVmg(cls, twsKn).up.twa - 5; }
/** Absolute speed cap (server move budget, speed clamps): RIGS[cls].vmaxKn, 0 for engine classes. */
export function maxSpeedKn(cls) { const r = rigOf(cls); return r ? r.vmaxKn : 0; }
