// World coverage (v7 step 0): real ports, fishing grounds and offshore fields beyond the North Sea detail region.
// Appended to HARBORS / FISHING_GROUNDS / PLATFORMS in server/harbors.js; ids are permanent (state, contracts, AIS links).
//
// Harbours: the position is the harbour entrance, roads or pilot station, on open water. Each anchor was checked against
// the world raster (Natural Earth 50 m, 0.05° cells; 10 m inside the North Sea window) and, where the town sits up a
// river or behind a coast the raster closes, moved to the nearest open-water cell at the entrance (≤ 12 km, Québec 35 km
// down the St. Lawrence). Sizes follow the port's real traffic (mega: world top-30 container/bulk hubs, major: national
// gateways and big bulk/oil terminals, regional, minor: island, fishing and feeder ports); fuelMul is the local bunker
// price relative to the world average (cheap at the bunkering hubs — Fujairah, Singapore, the Gulf — dear on remote islands).
// Every harbour is linked to the sea-lane graph (server/lanes.js + server/lanes-world.js) without crossing land.
export const WORLD_HARBORS = [
  // ---- Baltic, Gulf of Bothnia, Gulf of Finland ----
  { id: 'gdynia', name: 'Gdynia', country: 'PL', lat: 54.525, lon: 18.625, size: 'major', fuelMul: 0.97 },
  { id: 'swinoujscie', name: 'Świnoujście / Szczecin', country: 'PL', lat: 53.975, lon: 14.275, size: 'regional', fuelMul: 0.98 },
  { id: 'rostock', name: 'Rostock', country: 'DE', lat: 54.185, lon: 12.1, size: 'regional', fuelMul: 0.99 },
  { id: 'malmo', name: 'Malmö', country: 'SE', lat: 55.62, lon: 12.97, size: 'regional', fuelMul: 1.02 },
  { id: 'klaipeda', name: 'Klaipėda', country: 'LT', lat: 55.72, lon: 21.08, size: 'regional', fuelMul: 0.97 },
  { id: 'riga', name: 'Riga', country: 'LV', lat: 57.07, lon: 24.02, size: 'regional', fuelMul: 0.98 },
  { id: 'tallinn', name: 'Tallinn (Muuga)', country: 'EE', lat: 59.525, lon: 24.925, size: 'regional', fuelMul: 1 },
  { id: 'ust_luga', name: 'Ust-Luga', country: 'RU', lat: 59.725, lon: 28.375, size: 'major', fuelMul: 0.93 },
  { id: 'baltiysk', name: 'Baltiysk / Kaliningrad', country: 'RU', lat: 54.675, lon: 19.875, size: 'regional', fuelMul: 0.95 },
  { id: 'turku', name: 'Turku', country: 'FI', lat: 60.425, lon: 22.175, size: 'regional', fuelMul: 1.05 },
  { id: 'kotka', name: 'Kotka-Hamina', country: 'FI', lat: 60.475, lon: 26.975, size: 'regional', fuelMul: 1.04 },
  { id: 'lulea', name: 'Luleå', country: 'SE', lat: 65.58, lon: 22.15, size: 'regional', fuelMul: 1.08 },
  // ---- Norway north, Arctic, Atlantic islands ----
  { id: 'trondheim', name: 'Trondheim', country: 'NO', lat: 63.475, lon: 10.375, size: 'regional', fuelMul: 1.07 },
  { id: 'narvik', name: 'Narvik', country: 'NO', lat: 68.43, lon: 17.4, size: 'regional', fuelMul: 1.07 },
  { id: 'tromso', name: 'Tromsø', country: 'NO', lat: 69.65, lon: 18.96, size: 'minor', fuelMul: 1.09 },
  { id: 'hammerfest', name: 'Hammerfest', country: 'NO', lat: 70.675, lon: 23.625, size: 'minor', fuelMul: 1.1 },
  { id: 'kirkenes', name: 'Kirkenes', country: 'NO', lat: 69.775, lon: 30.025, size: 'minor', fuelMul: 1.1 },
  { id: 'arkhangelsk', name: 'Arkhangelsk', country: 'RU', lat: 64.9, lon: 40.2, size: 'regional', fuelMul: 1 },
  { id: 'torshavn', name: 'Tórshavn (Faroe)', country: 'FO', lat: 62.002, lon: -6.732, size: 'minor', fuelMul: 1.12 },
  { id: 'nuuk', name: 'Nuuk', country: 'GL', lat: 64.17, lon: -51.73, size: 'minor', fuelMul: 1.2 },
  // ---- British Isles, France Atlantic ----
  { id: 'belfast', name: 'Belfast', country: 'GB', lat: 54.63, lon: -5.88, size: 'major', fuelMul: 1.02 },
  { id: 'liverpool', name: 'Liverpool', country: 'GB', lat: 53.45, lon: -3.03, size: 'major', fuelMul: 1 },
  { id: 'milford_haven', name: 'Milford Haven', country: 'GB', lat: 51.7, lon: -5.05, size: 'major', fuelMul: 0.98 },
  { id: 'greenock', name: 'Glasgow (Greenock)', country: 'GB', lat: 55.953, lon: -4.768, size: 'regional', fuelMul: 1.03 },
  { id: 'cork', name: 'Cork', country: 'IE', lat: 51.8, lon: -8.27, size: 'regional', fuelMul: 1.04 },
  { id: 'saint_nazaire', name: 'Nantes Saint-Nazaire', country: 'FR', lat: 47.27, lon: -2.2, size: 'major', fuelMul: 0.99 },
  { id: 'bordeaux', name: 'Bordeaux (Le Verdon)', country: 'FR', lat: 45.57, lon: -1.07, size: 'regional', fuelMul: 1 },
  // ---- Iberia and Atlantic islands ----
  { id: 'bilbao', name: 'Bilbao', country: 'ES', lat: 43.425, lon: -3.075, size: 'major', fuelMul: 0.97 },
  { id: 'a_coruna', name: 'A Coruña', country: 'ES', lat: 43.425, lon: -8.375, size: 'regional', fuelMul: 0.98 },
  { id: 'vigo', name: 'Vigo', country: 'ES', lat: 42.225, lon: -8.775, size: 'regional', fuelMul: 0.97 },
  { id: 'leixoes', name: 'Leixões (Porto)', country: 'PT', lat: 41.175, lon: -8.725, size: 'regional', fuelMul: 0.99 },
  { id: 'sines', name: 'Sines', country: 'PT', lat: 37.94, lon: -8.88, size: 'major', fuelMul: 0.96 },
  { id: 'huelva', name: 'Huelva', country: 'ES', lat: 37.12, lon: -6.83, size: 'regional', fuelMul: 0.96 },
  { id: 'algeciras', name: 'Algeciras', country: 'ES', lat: 36.12, lon: -5.42, size: 'mega', fuelMul: 0.88 },
  { id: 'cartagena_es', name: 'Cartagena (Spain)', country: 'ES', lat: 37.525, lon: -0.975, size: 'regional', fuelMul: 0.97 },
  { id: 'valencia', name: 'Valencia', country: 'ES', lat: 39.44, lon: -0.3, size: 'mega', fuelMul: 0.95 },
  { id: 'barcelona', name: 'Barcelona', country: 'ES', lat: 41.325, lon: 2.175, size: 'major', fuelMul: 0.96 },
  { id: 'palma', name: 'Palma de Mallorca', country: 'ES', lat: 39.525, lon: 2.625, size: 'regional', fuelMul: 1 },
  { id: 'santa_cruz_tenerife', name: 'Santa Cruz de Tenerife', country: 'ES', lat: 28.425, lon: -16.225, size: 'regional', fuelMul: 0.96 },
  { id: 'ponta_delgada', name: 'Ponta Delgada (Azores)', country: 'PT', lat: 37.73, lon: -25.66, size: 'minor', fuelMul: 1.08 },
  // ---- Western and central Mediterranean ----
  { id: 'la_spezia', name: 'La Spezia', country: 'IT', lat: 44.075, lon: 9.825, size: 'major', fuelMul: 1.01 },
  { id: 'livorno', name: 'Livorno', country: 'IT', lat: 43.525, lon: 10.275, size: 'regional', fuelMul: 1.01 },
  { id: 'civitavecchia', name: 'Civitavecchia (Rome)', country: 'IT', lat: 42.075, lon: 11.775, size: 'regional', fuelMul: 1.02 },
  { id: 'naples', name: 'Naples', country: 'IT', lat: 40.775, lon: 14.275, size: 'major', fuelMul: 1.01 },
  { id: 'gioia_tauro', name: 'Gioia Tauro', country: 'IT', lat: 38.475, lon: 15.875, size: 'major', fuelMul: 0.98 },
  { id: 'palermo', name: 'Palermo', country: 'IT', lat: 38.125, lon: 13.425, size: 'regional', fuelMul: 1.02 },
  { id: 'taranto', name: 'Taranto', country: 'IT', lat: 40.475, lon: 17.175, size: 'major', fuelMul: 1 },
  { id: 'venice', name: 'Venice', country: 'IT', lat: 45.33, lon: 12.35, size: 'major', fuelMul: 1 },
  { id: 'trieste', name: 'Trieste', country: 'IT', lat: 45.64, lon: 13.74, size: 'major', fuelMul: 0.99 },
  { id: 'rijeka', name: 'Rijeka', country: 'HR', lat: 45.32, lon: 14.42, size: 'regional', fuelMul: 1 },
  { id: 'valletta', name: 'Valletta / Marsaxlokk', country: 'MT', lat: 35.825, lon: 14.575, size: 'major', fuelMul: 0.9 },
  // ---- Eastern Mediterranean, Black Sea ----
  { id: 'thessaloniki', name: 'Thessaloniki', country: 'GR', lat: 40.575, lon: 22.825, size: 'regional', fuelMul: 1 },
  { id: 'izmir', name: 'İzmir (outer gulf)', country: 'TR', lat: 38.475, lon: 26.875, size: 'regional', fuelMul: 0.98 },
  { id: 'mersin', name: 'Mersin', country: 'TR', lat: 36.775, lon: 34.625, size: 'major', fuelMul: 0.97 },
  { id: 'limassol', name: 'Limassol', country: 'CY', lat: 34.625, lon: 33.025, size: 'regional', fuelMul: 0.96 },
  { id: 'beirut', name: 'Beirut', country: 'LB', lat: 33.925, lon: 35.525, size: 'regional', fuelMul: 1 },
  { id: 'haifa', name: 'Haifa', country: 'IL', lat: 32.825, lon: 34.975, size: 'major', fuelMul: 1 },
  { id: 'ashdod', name: 'Ashdod', country: 'IL', lat: 31.83, lon: 34.63, size: 'regional', fuelMul: 1 },
  { id: 'port_said_east', name: 'Port Said East', country: 'EG', lat: 31.225, lon: 32.375, size: 'major', fuelMul: 0.93 },
  { id: 'constanta', name: 'Constanța', country: 'RO', lat: 44.175, lon: 28.675, size: 'major', fuelMul: 0.98 },
  { id: 'varna', name: 'Varna', country: 'BG', lat: 43.175, lon: 27.975, size: 'regional', fuelMul: 0.99 },
  { id: 'odesa', name: 'Odesa', country: 'UA', lat: 46.475, lon: 30.775, size: 'regional', fuelMul: 1 },
  { id: 'novorossiysk', name: 'Novorossiysk', country: 'RU', lat: 44.675, lon: 37.775, size: 'major', fuelMul: 0.94 },
  // ---- North and West Africa ----
  { id: 'tanger_med', name: 'Tanger Med', country: 'MA', lat: 35.875, lon: -5.525, size: 'mega', fuelMul: 0.9 },
  { id: 'casablanca', name: 'Casablanca', country: 'MA', lat: 33.625, lon: -7.625, size: 'major', fuelMul: 0.98 },
  { id: 'algiers', name: 'Algiers', country: 'DZ', lat: 36.825, lon: 3.075, size: 'regional', fuelMul: 0.95 },
  { id: 'tunis', name: 'Tunis (Radès)', country: 'TN', lat: 36.825, lon: 10.325, size: 'regional', fuelMul: 0.98 },
  { id: 'nouadhibou', name: 'Nouadhibou', country: 'MR', lat: 20.875, lon: -17.025, size: 'minor', fuelMul: 1.04 },
  { id: 'mindelo', name: 'Mindelo (Cabo Verde)', country: 'CV', lat: 16.925, lon: -24.975, size: 'minor', fuelMul: 1.08 },
  { id: 'freetown', name: 'Freetown', country: 'SL', lat: 8.525, lon: -13.225, size: 'minor', fuelMul: 1.06 },
  { id: 'monrovia', name: 'Monrovia', country: 'LR', lat: 6.325, lon: -10.825, size: 'minor', fuelMul: 1.05 },
  { id: 'abidjan', name: 'Abidjan', country: 'CI', lat: 5.25, lon: -4, size: 'major', fuelMul: 1 },
  { id: 'tema', name: 'Tema', country: 'GH', lat: 5.62, lon: 0.02, size: 'major', fuelMul: 1 },
  { id: 'lome', name: 'Lomé', country: 'TG', lat: 6.13, lon: 1.28, size: 'regional', fuelMul: 1 },
  { id: 'cotonou', name: 'Cotonou', country: 'BJ', lat: 6.325, lon: 2.425, size: 'regional', fuelMul: 1.01 },
  { id: 'lagos', name: 'Lagos (Apapa)', country: 'NG', lat: 6.4, lon: 3.4, size: 'major', fuelMul: 0.98 },
  { id: 'bonny', name: 'Bonny / Port Harcourt', country: 'NG', lat: 4.425, lon: 7.125, size: 'regional', fuelMul: 0.95 },
  { id: 'douala', name: 'Douala', country: 'CM', lat: 3.85, lon: 9.55, size: 'regional', fuelMul: 1.03 },
  { id: 'owendo', name: 'Libreville (Owendo)', country: 'GA', lat: 0.29, lon: 9.48, size: 'minor', fuelMul: 1.04 },
  { id: 'pointe_noire', name: 'Pointe-Noire', country: 'CG', lat: -4.78, lon: 11.83, size: 'regional', fuelMul: 1 },
  { id: 'luanda', name: 'Luanda', country: 'AO', lat: -8.78, lon: 13.24, size: 'regional', fuelMul: 0.98 },
  { id: 'walvis_bay', name: 'Walvis Bay', country: 'NA', lat: -22.875, lon: 14.425, size: 'regional', fuelMul: 1.03 },
  // ---- Southern and East Africa, Indian Ocean islands ----
  { id: 'saldanha', name: 'Saldanha Bay', country: 'ZA', lat: -33.025, lon: 17.925, size: 'regional', fuelMul: 1 },
  { id: 'ngqura', name: 'Port Elizabeth (Ngqura)', country: 'ZA', lat: -33.825, lon: 25.725, size: 'regional', fuelMul: 1 },
  { id: 'durban', name: 'Durban', country: 'ZA', lat: -29.875, lon: 31.075, size: 'major', fuelMul: 0.98 },
  { id: 'richards_bay', name: 'Richards Bay', country: 'ZA', lat: -28.825, lon: 32.075, size: 'major', fuelMul: 0.99 },
  { id: 'maputo', name: 'Maputo', country: 'MZ', lat: -25.975, lon: 32.625, size: 'regional', fuelMul: 1.02 },
  { id: 'beira', name: 'Beira', country: 'MZ', lat: -19.84, lon: 34.84, size: 'regional', fuelMul: 1.04 },
  { id: 'dar_es_salaam', name: 'Dar es Salaam', country: 'TZ', lat: -6.825, lon: 39.325, size: 'regional', fuelMul: 1.03 },
  { id: 'toamasina', name: 'Toamasina', country: 'MG', lat: -18.175, lon: 49.425, size: 'minor', fuelMul: 1.06 },
  { id: 'port_louis', name: 'Port Louis', country: 'MU', lat: -20.125, lon: 57.475, size: 'regional', fuelMul: 1 },
  { id: 'victoria_sc', name: 'Port Victoria (Seychelles)', country: 'SC', lat: -4.575, lon: 55.475, size: 'minor', fuelMul: 1.08 },
  { id: 'mogadishu', name: 'Mogadishu', country: 'SO', lat: 2.025, lon: 45.325, size: 'minor', fuelMul: 1.08 },
  { id: 'djibouti', name: 'Djibouti', country: 'DJ', lat: 11.6, lon: 43.13, size: 'major', fuelMul: 0.95 },
  // ---- Red Sea, Arabia, Persian Gulf ----
  { id: 'port_sudan', name: 'Port Sudan', country: 'SD', lat: 19.625, lon: 37.275, size: 'regional', fuelMul: 1.02 },
  { id: 'jeddah', name: 'Jeddah', country: 'SA', lat: 21.475, lon: 39.125, size: 'mega', fuelMul: 0.86 },
  { id: 'yanbu', name: 'Yanbu', country: 'SA', lat: 24.075, lon: 38.025, size: 'regional', fuelMul: 0.85 },
  { id: 'aqaba', name: 'Aqaba', country: 'JO', lat: 29.475, lon: 34.925, size: 'regional', fuelMul: 0.96 },
  { id: 'sokhna', name: 'Ain Sokhna', country: 'EG', lat: 29.625, lon: 32.425, size: 'regional', fuelMul: 0.93 },
  { id: 'aden', name: 'Aden', country: 'YE', lat: 12.775, lon: 44.975, size: 'regional', fuelMul: 0.98 },
  { id: 'salalah', name: 'Salalah', country: 'OM', lat: 16.925, lon: 54.025, size: 'major', fuelMul: 0.88 },
  { id: 'muscat', name: 'Muscat (Sultan Qaboos)', country: 'OM', lat: 23.675, lon: 58.575, size: 'minor', fuelMul: 0.88 },
  { id: 'sohar', name: 'Sohar', country: 'OM', lat: 24.525, lon: 56.625, size: 'major', fuelMul: 0.85 },
  { id: 'fujairah', name: 'Fujairah', country: 'AE', lat: 25.175, lon: 56.375, size: 'major', fuelMul: 0.78 },
  { id: 'abu_dhabi', name: 'Abu Dhabi (Khalifa)', country: 'AE', lat: 24.8, lon: 54.65, size: 'major', fuelMul: 0.8 },
  { id: 'doha', name: 'Doha (Hamad)', country: 'QA', lat: 25, lon: 51.65, size: 'major', fuelMul: 0.8 },
  { id: 'ras_laffan', name: 'Ras Laffan', country: 'QA', lat: 25.92, lon: 51.6, size: 'major', fuelMul: 0.8 },
  { id: 'bahrain', name: 'Bahrain (Khalifa bin Salman)', country: 'BH', lat: 26.18, lon: 50.72, size: 'regional', fuelMul: 0.82 },
  { id: 'dammam', name: 'Dammam', country: 'SA', lat: 26.5, lon: 50.2, size: 'major', fuelMul: 0.8 },
  { id: 'ras_tanura', name: 'Ras Tanura', country: 'SA', lat: 26.65, lon: 50.17, size: 'major', fuelMul: 0.78 },
  { id: 'kuwait', name: 'Kuwait (Shuaiba)', country: 'KW', lat: 29.025, lon: 48.175, size: 'regional', fuelMul: 0.8 },
  { id: 'umm_qasr', name: 'Umm Qasr', country: 'IQ', lat: 29.825, lon: 48.025, size: 'regional', fuelMul: 0.82 },
  { id: 'kharg', name: 'Kharg Island', country: 'IR', lat: 29.23, lon: 50.32, size: 'regional', fuelMul: 0.75 },
  { id: 'bandar_abbas', name: 'Bandar Abbas', country: 'IR', lat: 27.075, lon: 56.125, size: 'major', fuelMul: 0.8 },
  // ---- South Asia ----
  { id: 'karachi', name: 'Karachi', country: 'PK', lat: 24.775, lon: 66.925, size: 'major', fuelMul: 0.92 },
  { id: 'mundra', name: 'Mundra / Kandla', country: 'IN', lat: 22.725, lon: 69.675, size: 'major', fuelMul: 0.9 },
  { id: 'mormugao', name: 'Mormugão (Goa)', country: 'IN', lat: 15.42, lon: 73.78, size: 'regional', fuelMul: 0.94 },
  { id: 'kochi', name: 'Kochi', country: 'IN', lat: 9.97, lon: 76.24, size: 'regional', fuelMul: 0.94 },
  { id: 'chennai', name: 'Chennai', country: 'IN', lat: 13.075, lon: 80.325, size: 'major', fuelMul: 0.93 },
  { id: 'visakhapatnam', name: 'Visakhapatnam', country: 'IN', lat: 17.68, lon: 83.29, size: 'major', fuelMul: 0.93 },
  { id: 'paradip', name: 'Paradip', country: 'IN', lat: 20.275, lon: 86.725, size: 'regional', fuelMul: 0.94 },
  { id: 'haldia', name: 'Kolkata (Haldia / Sagar Roads)', country: 'IN', lat: 21.6, lon: 88.1, size: 'regional', fuelMul: 0.95 },
  { id: 'chittagong', name: 'Chittagong', country: 'BD', lat: 22.2, lon: 91.8, size: 'major', fuelMul: 0.96 },
  { id: 'yangon', name: 'Yangon (Elephant Point)', country: 'MM', lat: 16.475, lon: 96.325, size: 'regional', fuelMul: 0.98 },
  { id: 'male', name: 'Malé', country: 'MV', lat: 4.18, lon: 73.51, size: 'minor', fuelMul: 1.1 },
  // ---- South-east Asia ----
  { id: 'port_klang', name: 'Port Klang', country: 'MY', lat: 3.075, lon: 101.325, size: 'mega', fuelMul: 0.88 },
  { id: 'penang', name: 'Penang', country: 'MY', lat: 5.41, lon: 100.35, size: 'regional', fuelMul: 0.9 },
  { id: 'tanjung_pelepas', name: 'Tanjung Pelepas', country: 'MY', lat: 1.325, lon: 103.575, size: 'mega', fuelMul: 0.86 },
  { id: 'bintulu', name: 'Bintulu', country: 'MY', lat: 3.27, lon: 113.07, size: 'regional', fuelMul: 0.9 },
  { id: 'kemaman', name: 'Kemaman (Kerteh supply base)', country: 'MY', lat: 4.24, lon: 103.47, size: 'minor', fuelMul: 0.9 },
  { id: 'kota_kinabalu', name: 'Kota Kinabalu', country: 'MY', lat: 6, lon: 116.07, size: 'minor', fuelMul: 0.95 },
  { id: 'muara', name: 'Muara (Brunei)', country: 'BN', lat: 5.03, lon: 115.07, size: 'minor', fuelMul: 0.88 },
  { id: 'batam', name: 'Batam', country: 'ID', lat: 1.175, lon: 103.975, size: 'regional', fuelMul: 0.88 },
  { id: 'belawan', name: 'Belawan (Medan)', country: 'ID', lat: 3.825, lon: 98.725, size: 'regional', fuelMul: 0.94 },
  { id: 'surabaya', name: 'Surabaya (Tanjung Perak)', country: 'ID', lat: -7.2, lon: 112.72, size: 'major', fuelMul: 0.93 },
  { id: 'makassar', name: 'Makassar', country: 'ID', lat: -5.125, lon: 119.375, size: 'regional', fuelMul: 0.95 },
  { id: 'balikpapan', name: 'Balikpapan', country: 'ID', lat: -1.28, lon: 116.8, size: 'regional', fuelMul: 0.9 },
  { id: 'laem_chabang', name: 'Laem Chabang', country: 'TH', lat: 13.07, lon: 100.88, size: 'mega', fuelMul: 0.92 },
  { id: 'sihanoukville', name: 'Sihanoukville', country: 'KH', lat: 10.64, lon: 103.5, size: 'minor', fuelMul: 0.97 },
  { id: 'vung_tau', name: 'Ho Chi Minh City (Cái Mép / Vũng Tàu)', country: 'VN', lat: 10.33, lon: 107.05, size: 'major', fuelMul: 0.93 },
  { id: 'da_nang', name: 'Da Nang', country: 'VN', lat: 16.13, lon: 108.22, size: 'minor', fuelMul: 0.95 },
  { id: 'haiphong', name: 'Haiphong (Lạch Huyện)', country: 'VN', lat: 20.67, lon: 106.8, size: 'major', fuelMul: 0.93 },
  { id: 'cebu', name: 'Cebu', country: 'PH', lat: 10.275, lon: 123.925, size: 'regional', fuelMul: 0.98 },
  { id: 'subic', name: 'Subic Bay', country: 'PH', lat: 14.725, lon: 120.225, size: 'regional', fuelMul: 0.97 },
  { id: 'dili', name: 'Dili', country: 'TL', lat: -8.525, lon: 125.575, size: 'minor', fuelMul: 1.05 },
  // ---- East Asia ----
  { id: 'shenzhen', name: 'Shenzhen (Yantian)', country: 'CN', lat: 22.525, lon: 114.325, size: 'mega', fuelMul: 0.9 },
  { id: 'guangzhou', name: 'Guangzhou (Nansha)', country: 'CN', lat: 22.65, lon: 113.68, size: 'mega', fuelMul: 0.9 },
  { id: 'xiamen', name: 'Xiamen', country: 'CN', lat: 24.45, lon: 118.07, size: 'major', fuelMul: 0.91 },
  { id: 'ningbo', name: 'Ningbo-Zhoushan', country: 'CN', lat: 29.93, lon: 121.95, size: 'mega', fuelMul: 0.89 },
  { id: 'qingdao', name: 'Qingdao', country: 'CN', lat: 36.03, lon: 120.32, size: 'mega', fuelMul: 0.9 },
  { id: 'tianjin', name: 'Tianjin', country: 'CN', lat: 38.97, lon: 117.85, size: 'mega', fuelMul: 0.9 },
  { id: 'dalian', name: 'Dalian', country: 'CN', lat: 38.93, lon: 121.72, size: 'major', fuelMul: 0.91 },
  { id: 'kaohsiung', name: 'Kaohsiung', country: 'TW', lat: 22.575, lon: 120.275, size: 'mega', fuelMul: 0.92 },
  { id: 'incheon', name: 'Incheon', country: 'KR', lat: 37.45, lon: 126.6, size: 'major', fuelMul: 0.94 },
  { id: 'gwangyang', name: 'Gwangyang', country: 'KR', lat: 34.9, lon: 127.7, size: 'major', fuelMul: 0.93 },
  { id: 'ulsan', name: 'Ulsan', country: 'KR', lat: 35.475, lon: 129.425, size: 'major', fuelMul: 0.92 },
  { id: 'vladivostok', name: 'Vladivostok', country: 'RU', lat: 43.125, lon: 131.875, size: 'regional', fuelMul: 0.96 },
  { id: 'nakhodka', name: 'Nakhodka (Vostochny)', country: 'RU', lat: 42.725, lon: 133.025, size: 'regional', fuelMul: 0.96 },
  { id: 'korsakov', name: 'Korsakov (Sakhalin)', country: 'RU', lat: 46.62, lon: 142.77, size: 'minor', fuelMul: 1 },
  { id: 'petropavlovsk', name: 'Petropavlovsk-Kamchatsky', country: 'RU', lat: 52.975, lon: 158.625, size: 'minor', fuelMul: 1.05 },
  { id: 'kobe', name: 'Kobe / Osaka', country: 'JP', lat: 34.625, lon: 135.225, size: 'mega', fuelMul: 1 },
  { id: 'nagoya', name: 'Nagoya', country: 'JP', lat: 34.975, lon: 136.825, size: 'major', fuelMul: 1 },
  { id: 'hakata', name: 'Fukuoka (Hakata)', country: 'JP', lat: 33.625, lon: 130.325, size: 'regional', fuelMul: 1 },
  { id: 'niigata', name: 'Niigata', country: 'JP', lat: 37.975, lon: 139.075, size: 'regional', fuelMul: 1.02 },
  { id: 'tomakomai', name: 'Tomakomai (Hokkaido)', country: 'JP', lat: 42.525, lon: 141.625, size: 'regional', fuelMul: 1.02 },
  // ---- Australia, New Zealand, Pacific islands ----
  { id: 'melbourne', name: 'Melbourne (Port Phillip Heads)', country: 'AU', lat: -38.3, lon: 144.62, size: 'major', fuelMul: 1.04 },
  { id: 'brisbane', name: 'Brisbane (Moreton Bay)', country: 'AU', lat: -27.325, lon: 153.175, size: 'major', fuelMul: 1.04 },
  { id: 'fremantle', name: 'Fremantle (Perth)', country: 'AU', lat: -32.075, lon: 115.725, size: 'major', fuelMul: 1.03 },
  { id: 'adelaide', name: 'Adelaide', country: 'AU', lat: -34.775, lon: 138.475, size: 'regional', fuelMul: 1.05 },
  { id: 'port_hedland', name: 'Port Hedland', country: 'AU', lat: -20.275, lon: 118.575, size: 'major', fuelMul: 1.04 },
  { id: 'dampier', name: 'Dampier', country: 'AU', lat: -20.62, lon: 116.72, size: 'regional', fuelMul: 1.04 },
  { id: 'broome', name: 'Broome', country: 'AU', lat: -17.99, lon: 122.21, size: 'minor', fuelMul: 1.08 },
  { id: 'darwin', name: 'Darwin', country: 'AU', lat: -12.47, lon: 130.83, size: 'regional', fuelMul: 1.06 },
  { id: 'newcastle_au', name: 'Newcastle (NSW)', country: 'AU', lat: -32.925, lon: 151.825, size: 'major', fuelMul: 1.04 },
  { id: 'gladstone', name: 'Gladstone', country: 'AU', lat: -23.825, lon: 151.275, size: 'major', fuelMul: 1.05 },
  { id: 'hay_point', name: 'Hay Point / Mackay', country: 'AU', lat: -21.27, lon: 149.32, size: 'regional', fuelMul: 1.05 },
  { id: 'hobart', name: 'Hobart', country: 'AU', lat: -42.925, lon: 147.375, size: 'minor', fuelMul: 1.08 },
  { id: 'wellington', name: 'Wellington', country: 'NZ', lat: -41.325, lon: 174.775, size: 'regional', fuelMul: 1.08 },
  { id: 'tauranga', name: 'Tauranga', country: 'NZ', lat: -37.625, lon: 176.175, size: 'regional', fuelMul: 1.07 },
  { id: 'lyttelton', name: 'Lyttelton (Christchurch)', country: 'NZ', lat: -43.575, lon: 172.825, size: 'minor', fuelMul: 1.09 },
  { id: 'nelson', name: 'Nelson', country: 'NZ', lat: -41.225, lon: 173.275, size: 'minor', fuelMul: 1.09 },
  { id: 'port_moresby', name: 'Port Moresby', country: 'PG', lat: -9.475, lon: 147.125, size: 'minor', fuelMul: 1.1 },
  { id: 'suva', name: 'Suva', country: 'FJ', lat: -18.13, lon: 178.42, size: 'minor', fuelMul: 1.12 },
  { id: 'noumea', name: 'Nouméa', country: 'NC', lat: -22.27, lon: 166.43, size: 'minor', fuelMul: 1.12 },
  { id: 'papeete', name: 'Papeete (Tahiti)', country: 'PF', lat: -17.525, lon: -149.625, size: 'minor', fuelMul: 1.18 },
  { id: 'apia', name: 'Apia', country: 'WS', lat: -13.82, lon: -171.76, size: 'minor', fuelMul: 1.18 },
  { id: 'apra', name: 'Apra Harbor (Guam)', country: 'GU', lat: 13.475, lon: 144.625, size: 'minor', fuelMul: 1.1 },
  // ---- North America, Pacific coast ----
  { id: 'dutch_harbor', name: 'Unalaska (Dutch Harbor)', country: 'US', lat: 53.89, lon: -166.53, size: 'minor', fuelMul: 1.1 },
  { id: 'kodiak', name: 'Kodiak', country: 'US', lat: 57.79, lon: -152.4, size: 'minor', fuelMul: 1.1 },
  { id: 'anchorage', name: 'Port of Alaska (Anchorage)', country: 'US', lat: 61.225, lon: -149.925, size: 'regional', fuelMul: 1.08 },
  { id: 'prince_rupert', name: 'Prince Rupert', country: 'CA', lat: 54.275, lon: -130.375, size: 'regional', fuelMul: 1.04 },
  { id: 'seattle', name: 'Seattle / Tacoma', country: 'US', lat: 47.575, lon: -122.375, size: 'major', fuelMul: 1.02 },
  { id: 'oakland', name: 'San Francisco / Oakland', country: 'US', lat: 37.8, lon: -122.33, size: 'major', fuelMul: 1.04 },
  { id: 'san_diego', name: 'San Diego', country: 'US', lat: 32.625, lon: -117.175, size: 'regional', fuelMul: 1.04 },
  { id: 'manzanillo_mx', name: 'Manzanillo (Mexico)', country: 'MX', lat: 19.025, lon: -104.325, size: 'major', fuelMul: 0.96 },
  { id: 'lazaro_cardenas', name: 'Lázaro Cárdenas', country: 'MX', lat: 17.925, lon: -102.175, size: 'major', fuelMul: 0.96 },
  { id: 'puerto_quetzal', name: 'Puerto Quetzal', country: 'GT', lat: 13.92, lon: -90.78, size: 'minor', fuelMul: 1 },
  { id: 'caldera_cr', name: 'Caldera (Costa Rica)', country: 'CR', lat: 9.875, lon: -84.725, size: 'minor', fuelMul: 1.02 },
  { id: 'balboa', name: 'Balboa (Panama)', country: 'PA', lat: 8.925, lon: -79.525, size: 'major', fuelMul: 0.93 },
  // ---- North America, Gulf and Atlantic coast ----
  { id: 'corpus_christi', name: 'Corpus Christi (Port Aransas)', country: 'US', lat: 27.8, lon: -97.05, size: 'major', fuelMul: 0.88 },
  { id: 'new_orleans', name: 'New Orleans (Southwest Pass)', country: 'US', lat: 28.9, lon: -89.43, size: 'major', fuelMul: 0.9 },
  { id: 'tampa', name: 'Tampa (Egmont Key)', country: 'US', lat: 27.6, lon: -82.75, size: 'regional', fuelMul: 0.95 },
  { id: 'veracruz', name: 'Veracruz', country: 'MX', lat: 19.225, lon: -96.125, size: 'major', fuelMul: 0.95 },
  { id: 'miami', name: 'Miami / Port Everglades', country: 'US', lat: 25.76, lon: -80.12, size: 'major', fuelMul: 0.98 },
  { id: 'savannah', name: 'Savannah', country: 'US', lat: 32.03, lon: -80.85, size: 'major', fuelMul: 0.97 },
  { id: 'charleston', name: 'Charleston', country: 'US', lat: 32.75, lon: -79.85, size: 'major', fuelMul: 0.97 },
  { id: 'norfolk', name: 'Norfolk (Hampton Roads)', country: 'US', lat: 36.95, lon: -76.05, size: 'major', fuelMul: 0.97 },
  { id: 'baltimore', name: 'Baltimore', country: 'US', lat: 39.225, lon: -76.475, size: 'major', fuelMul: 0.98 },
  { id: 'boston', name: 'Boston', country: 'US', lat: 42.35, lon: -70.95, size: 'major', fuelMul: 1 },
  { id: 'quebec', name: 'Québec (lower St. Lawrence)', country: 'CA', lat: 47.025, lon: -70.875, size: 'regional', fuelMul: 1.03 },
  { id: 'sept_iles', name: 'Sept-Îles', country: 'CA', lat: 50.175, lon: -66.375, size: 'regional', fuelMul: 1.04 },
  { id: 'st_johns', name: "St. John's (Newfoundland)", country: 'CA', lat: 47.575, lon: -52.625, size: 'regional', fuelMul: 1.05 },
  // ---- Caribbean, Central America ----
  { id: 'freeport_bs', name: 'Freeport (Bahamas)', country: 'BS', lat: 26.475, lon: -78.775, size: 'major', fuelMul: 0.95 },
  { id: 'havana', name: 'Havana (Mariel)', country: 'CU', lat: 23.175, lon: -82.325, size: 'regional', fuelMul: 1.02 },
  { id: 'kingston', name: 'Kingston', country: 'JM', lat: 17.925, lon: -76.825, size: 'major', fuelMul: 0.97 },
  { id: 'caucedo', name: 'Santo Domingo (Caucedo)', country: 'DO', lat: 18.425, lon: -69.625, size: 'regional', fuelMul: 0.98 },
  { id: 'san_juan', name: 'San Juan', country: 'PR', lat: 18.475, lon: -66.125, size: 'regional', fuelMul: 1 },
  { id: 'fort_de_france', name: 'Fort-de-France', country: 'MQ', lat: 14.625, lon: -61.125, size: 'minor', fuelMul: 1.05 },
  { id: 'port_of_spain', name: 'Port of Spain', country: 'TT', lat: 10.625, lon: -61.525, size: 'regional', fuelMul: 0.94 },
  { id: 'willemstad', name: 'Willemstad (Curaçao)', country: 'CW', lat: 12.075, lon: -68.925, size: 'minor', fuelMul: 0.95 },
  { id: 'cartagena_co', name: 'Cartagena (Colombia)', country: 'CO', lat: 10.425, lon: -75.525, size: 'major', fuelMul: 0.95 },
  { id: 'puerto_cabello', name: 'Puerto Cabello', country: 'VE', lat: 10.525, lon: -68.025, size: 'regional', fuelMul: 0.9 },
  { id: 'puerto_cortes', name: 'Puerto Cortés', country: 'HN', lat: 15.825, lon: -87.975, size: 'regional', fuelMul: 0.98 },
  // ---- South America ----
  { id: 'georgetown', name: 'Georgetown', country: 'GY', lat: 6.875, lon: -58.175, size: 'minor', fuelMul: 1.02 },
  { id: 'belem', name: 'Belém (Vila do Conde)', country: 'BR', lat: -1.4, lon: -48.5, size: 'regional', fuelMul: 1 },
  { id: 'itaqui', name: 'São Luís (Itaqui)', country: 'BR', lat: -2.57, lon: -44.37, size: 'major', fuelMul: 0.98 },
  { id: 'pecem', name: 'Fortaleza (Pecém)', country: 'BR', lat: -3.53, lon: -38.8, size: 'regional', fuelMul: 0.99 },
  { id: 'suape', name: 'Recife (Suape)', country: 'BR', lat: -8.425, lon: -34.925, size: 'regional', fuelMul: 0.99 },
  { id: 'salvador', name: 'Salvador', country: 'BR', lat: -12.96, lon: -38.52, size: 'regional', fuelMul: 1 },
  { id: 'vitoria', name: 'Vitória (Tubarão)', country: 'BR', lat: -20.28, lon: -40.24, size: 'major', fuelMul: 0.98 },
  { id: 'itaguai', name: 'Itaguaí (Sepetiba)', country: 'BR', lat: -22.93, lon: -43.83, size: 'major', fuelMul: 0.98 },
  { id: 'paranagua', name: 'Paranaguá', country: 'BR', lat: -25.525, lon: -48.475, size: 'major', fuelMul: 0.98 },
  { id: 'itajai', name: 'Itajaí / Navegantes', country: 'BR', lat: -26.925, lon: -48.575, size: 'regional', fuelMul: 0.99 },
  { id: 'rio_grande', name: 'Rio Grande', country: 'BR', lat: -32.15, lon: -52.08, size: 'major', fuelMul: 0.99 },
  { id: 'montevideo', name: 'Montevideo', country: 'UY', lat: -34.92, lon: -56.21, size: 'major', fuelMul: 1 },
  { id: 'bahia_blanca', name: 'Bahía Blanca', country: 'AR', lat: -38.825, lon: -62.225, size: 'regional', fuelMul: 1 },
  { id: 'mar_del_plata', name: 'Mar del Plata', country: 'AR', lat: -38.025, lon: -57.525, size: 'minor', fuelMul: 1 },
  { id: 'puerto_madryn', name: 'Puerto Madryn', country: 'AR', lat: -42.725, lon: -64.975, size: 'minor', fuelMul: 1.03 },
  { id: 'ushuaia', name: 'Ushuaia', country: 'AR', lat: -54.825, lon: -68.275, size: 'minor', fuelMul: 1.1 },
  { id: 'stanley', name: 'Stanley (Falklands)', country: 'FK', lat: -51.68, lon: -57.78, size: 'minor', fuelMul: 1.15 },
  { id: 'punta_arenas', name: 'Punta Arenas', country: 'CL', lat: -53.175, lon: -70.925, size: 'minor', fuelMul: 1.08 },
  { id: 'puerto_montt', name: 'Puerto Montt', country: 'CL', lat: -41.525, lon: -72.925, size: 'minor', fuelMul: 1.05 },
  { id: 'talcahuano', name: 'Talcahuano / San Vicente', country: 'CL', lat: -36.73, lon: -73.13, size: 'regional', fuelMul: 1.02 },
  { id: 'san_antonio', name: 'San Antonio (Chile)', country: 'CL', lat: -33.575, lon: -71.675, size: 'major', fuelMul: 1.02 },
  { id: 'antofagasta', name: 'Antofagasta', country: 'CL', lat: -23.675, lon: -70.425, size: 'regional', fuelMul: 1.02 },
  { id: 'callao', name: 'Callao (Lima)', country: 'PE', lat: -12.05, lon: -77.17, size: 'major', fuelMul: 0.98 },
  { id: 'chimbote', name: 'Chimbote', country: 'PE', lat: -9.075, lon: -78.625, size: 'minor', fuelMul: 1 },
  { id: 'posorja', name: 'Guayaquil (Posorja)', country: 'EC', lat: -2.725, lon: -80.225, size: 'major', fuelMul: 0.97 },
  { id: 'manta', name: 'Manta', country: 'EC', lat: -0.925, lon: -80.725, size: 'minor', fuelMul: 0.98 },
  { id: 'buenaventura', name: 'Buenaventura', country: 'CO', lat: 3.825, lon: -77.175, size: 'regional', fuelMul: 0.98 },
];

// Major commercial fishing grounds of the world (centre on the bank/shelf, radius of the fished area, richness relative
// to the Dogger Bank = 1.0; upwelling systems and the great shelves rate highest).
export const WORLD_FISHING_GROUNDS = [
  // North Atlantic and Arctic
  { id: 'georges_bank', name: 'Georges Bank', lat: 41.4, lon: -67.6, radiusKm: 120, richness: 1.3 },
  { id: 'scotian_shelf', name: 'Scotian Shelf', lat: 44.0, lon: -61.5, radiusKm: 130, richness: 1.0 },
  { id: 'flemish_cap', name: 'Flemish Cap', lat: 47.0, lon: -45.0, radiusKm: 90, richness: 1.1 },
  { id: 'west_greenland', name: 'West Greenland banks', lat: 65.5, lon: -54.5, radiusKm: 150, richness: 1.1 },
  { id: 'iceland_south', name: 'Selvogsbanki (south Iceland)', lat: 63.4, lon: -20.8, radiusKm: 130, richness: 1.3 },
  { id: 'iceland_north', name: 'North Iceland shelf', lat: 66.8, lon: -18.0, radiusKm: 130, richness: 1.1 },
  { id: 'faroe_plateau', name: 'Faroe Plateau', lat: 62.3, lon: -7.6, radiusKm: 110, richness: 1.1 },
  { id: 'west_of_scotland', name: 'West of Scotland (St Kilda grounds)', lat: 57.8, lon: -8.8, radiusKm: 100, richness: 0.9 },
  { id: 'celtic_sea', name: 'Celtic Sea', lat: 51.0, lon: -7.5, radiusKm: 120, richness: 0.9 },
  { id: 'norwegian_sea', name: 'Norwegian Sea (herring and mackerel)', lat: 66.0, lon: 5.0, radiusKm: 250, richness: 1.2 },
  { id: 'lofoten', name: 'Lofoten cod grounds (Vestfjorden)', lat: 68.0, lon: 14.2, radiusKm: 90, richness: 1.4 },
  { id: 'barents_sea', name: 'Barents Sea', lat: 71.8, lon: 31.0, radiusKm: 300, richness: 1.5 },
  { id: 'central_baltic', name: 'Central Baltic (sprat and herring)', lat: 56.3, lon: 19.0, radiusKm: 120, richness: 0.7 },
  // Mediterranean and Black Sea
  { id: 'adriatic', name: 'Adriatic (sardine and anchovy)', lat: 43.3, lon: 14.8, radiusKm: 150, richness: 0.8 },
  { id: 'sicily_channel', name: 'Strait of Sicily', lat: 36.9, lon: 12.6, radiusKm: 120, richness: 0.8 },
  { id: 'gulf_of_lion', name: 'Gulf of Lion', lat: 43.0, lon: 4.2, radiusKm: 90, richness: 0.7 },
  { id: 'black_sea', name: 'Black Sea anchovy grounds', lat: 42.3, lon: 34.5, radiusKm: 150, richness: 0.8 },
  // Africa and the Indian Ocean
  { id: 'saharan_bank', name: 'Canary Current (Saharan Bank)', lat: 25.5, lon: -16.0, radiusKm: 220, richness: 1.4 },
  { id: 'mauritania', name: 'Mauritanian shelf', lat: 19.5, lon: -17.3, radiusKm: 150, richness: 1.4 },
  { id: 'senegal_shelf', name: 'Senegal shelf', lat: 14.2, lon: -17.8, radiusKm: 110, richness: 1.1 },
  { id: 'agulhas_bank', name: 'Agulhas Bank', lat: -35.3, lon: 21.5, radiusKm: 150, richness: 1.1 },
  { id: 'arabian_sea_oman', name: 'Arabian Sea (Oman upwelling)', lat: 18.5, lon: 57.8, radiusKm: 200, richness: 1.3 },
  { id: 'malabar', name: 'Malabar coast (oil sardine)', lat: 11.5, lon: 74.8, radiusKm: 170, richness: 1.2 },
  { id: 'bay_of_bengal', name: 'Northern Bay of Bengal (hilsa)', lat: 20.6, lon: 89.8, radiusKm: 150, richness: 1.1 },
  // Asia and the Pacific
  { id: 'gulf_of_thailand', name: 'Gulf of Thailand', lat: 9.5, lon: 101.5, radiusKm: 220, richness: 1.1 },
  { id: 'south_china_sea', name: 'Pearl River shelf (South China Sea)', lat: 21.0, lon: 115.0, radiusKm: 200, richness: 1.2 },
  { id: 'gulf_of_tonkin', name: 'Gulf of Tonkin', lat: 19.8, lon: 107.6, radiusKm: 130, richness: 1.0 },
  { id: 'zhoushan', name: 'Zhoushan grounds (East China Sea)', lat: 30.0, lon: 123.5, radiusKm: 200, richness: 1.5 },
  { id: 'yellow_sea', name: 'Yellow Sea', lat: 35.5, lon: 123.5, radiusKm: 220, richness: 1.2 },
  { id: 'sanriku', name: 'Sanriku (Kuroshio–Oyashio front)', lat: 39.0, lon: 143.0, radiusKm: 150, richness: 1.4 },
  { id: 'sea_of_okhotsk', name: 'Sea of Okhotsk (pollock)', lat: 53.0, lon: 150.5, radiusKm: 350, richness: 1.4 },
  { id: 'bering_sea', name: 'Bering Sea (pollock)', lat: 56.5, lon: -167.0, radiusKm: 330, richness: 1.6 },
  { id: 'gulf_of_alaska', name: 'Gulf of Alaska', lat: 57.0, lon: -151.0, radiusKm: 220, richness: 1.2 },
  { id: 'chatham_rise', name: 'Chatham Rise', lat: -43.6, lon: 177.0, radiusKm: 250, richness: 1.2 },
  { id: 'se_australia', name: 'South East Trawl (off Eden)', lat: -37.6, lon: 150.4, radiusKm: 120, richness: 0.8 },
  { id: 'great_australian_bight', name: 'Great Australian Bight (sardine)', lat: -35.3, lon: 135.4, radiusKm: 150, richness: 0.9 },
  // The Americas
  { id: 'gulf_of_mexico', name: 'Gulf of Mexico shrimp grounds', lat: 28.6, lon: -92.5, radiusKm: 180, richness: 1.1 },
  { id: 'campeche_bank', name: 'Campeche Bank', lat: 21.8, lon: -91.0, radiusKm: 150, richness: 0.9 },
  { id: 'caribbean', name: 'Pedro Bank (Caribbean)', lat: 17.0, lon: -78.0, radiusKm: 90, richness: 0.7 },
  { id: 'humboldt', name: 'Humboldt Current (Peruvian anchoveta)', lat: -10.0, lon: -79.3, radiusKm: 300, richness: 1.8 },
  { id: 'chile_central', name: 'Central Chile (jack mackerel)', lat: -36.5, lon: -74.2, radiusKm: 200, richness: 1.2 },
  { id: 'patagonian_shelf', name: 'Patagonian Shelf (hake and squid)', lat: -45.0, lon: -62.0, radiusKm: 350, richness: 1.4 },
  { id: 'falklands', name: 'Falkland Islands (Loligo squid)', lat: -51.0, lon: -58.0, radiusKm: 180, richness: 1.3 },
  { id: 'south_brazil', name: 'South Brazil Bight', lat: -26.5, lon: -47.0, radiusKm: 150, richness: 0.8 },
];

// Offshore oil and gas installations (real field positions) served by supply contracts.
export const WORLD_PLATFORMS = [
  { id: 'thunder_horse', name: 'Thunder Horse (Gulf of Mexico)', lat: 28.19, lon: -88.5 },
  { id: 'perdido', name: 'Perdido spar (Gulf of Mexico)', lat: 26.13, lon: -94.9 },
  { id: 'cantarell', name: 'Cantarell Akal-C (Bay of Campeche)', lat: 19.4, lon: -92.2 },
  { id: 'hibernia', name: 'Hibernia GBS (Grand Banks)', lat: 46.75, lon: -48.78 },
  { id: 'tupi', name: 'Tupi FPSOs (Santos Basin)', lat: -25.4, lon: -42.8 },
  { id: 'buzios', name: 'Búzios FPSOs (Santos Basin)', lat: -24.7, lon: -42.4 },
  { id: 'jubilee', name: 'Jubilee FPSO (Ghana)', lat: 4.6, lon: -2.95 },
  { id: 'bonga', name: 'Bonga FPSO (Nigeria)', lat: 4.55, lon: 4.6 },
  { id: 'girassol', name: 'Girassol FPSO (Angola Block 17)', lat: -7.5, lon: 12.2 },
  { id: 'safaniya', name: 'Safaniya (Saudi Arabia)', lat: 28.1, lon: 49.0 },
  { id: 'upper_zakum', name: 'Upper Zakum (Abu Dhabi)', lat: 24.9, lon: 53.7 },
  { id: 'bombay_high', name: 'Mumbai High', lat: 19.42, lon: 71.33 },
  { id: 'north_rankin', name: 'North Rankin (North West Shelf)', lat: -19.59, lon: 116.14 },
  { id: 'prelude', name: 'Prelude FLNG (Browse Basin)', lat: -13.79, lon: 123.31 },
  { id: 'tapis', name: 'Tapis (Malay Basin)', lat: 5.52, lon: 105.0 },
  { id: 'ampa', name: 'Southwest Ampa (Brunei)', lat: 4.85, lon: 114.4 },
  { id: 'bach_ho', name: 'Bạch Hổ / White Tiger (Vietnam)', lat: 9.9, lon: 108.0 },
  { id: 'penglai', name: 'Penglai 19-3 (Bohai Bay)', lat: 38.35, lon: 120.1 },
  { id: 'molikpaq', name: 'Molikpaq PA-A (Sakhalin-2)', lat: 52.85, lon: 143.57 },
  { id: 'lunskoye', name: 'Lunskoye-A (Sakhalin-2)', lat: 51.4, lon: 143.65 },
  { id: 'heidrun', name: 'Heidrun TLP (Norwegian Sea)', lat: 65.33, lon: 7.32 },
  { id: 'draugen', name: 'Draugen (Norwegian Sea)', lat: 64.35, lon: 7.78 },
  { id: 'aasta_hansteen', name: 'Aasta Hansteen spar (Norwegian Sea)', lat: 67.07, lon: 6.93 },
  { id: 'goliat', name: 'Goliat FPSO (Barents Sea)', lat: 71.29, lon: 22.3 },
  { id: 'johan_castberg', name: 'Johan Castberg FPSO (Barents Sea)', lat: 72.5, lon: 20.3 },
];
