// World-coverage sea lanes (v7 step 0): waypoints and edges that extend the coarse global layer of server/lanes.js so every
// harbour in server/harbors-world.js is reachable along water — the Baltic and the Gulf of Bothnia, the Norwegian coast and
// the White Sea, the Kiel Canal, Iberia, the Adriatic, the Levant, the Bosporus and the Black Sea, West, South and East
// Africa, the Red Sea and the Persian Gulf, India and the Bay of Bengal, the Malacca Strait, the Gulf of Thailand, the
// Indonesian straits (Lombok, Makassar), Vietnam, the Taiwan Strait, the Yellow Sea and the Bohai, Japan, the Sea of
// Okhotsk and Kamchatka, the Aleutians and Alaska, both American coasts, the Gulf of Mexico, the Caribbean passages, the
// Gulf of St Lawrence, Brazil, Argentina, the Strait of Magellan, Chile and Peru, Australia, New Zealand and the Pacific
// islands. Every coordinate is open water on the world raster; buildGraph() still verifies each edge at 2 km steps.
// `canal` edges are man-made canals (Kiel) or straits the 5 km raster cannot resolve (Bosporus, Messina, Torres, the
// First Narrows of Magellan): they skip the water check like the Suez and Panama edges.
import { DEEP_MOVES, DEEP_VIAS } from './lanes-deep.js';
const N = (id, name, lat, lon, kind = 'ocean') => ({ id, name, lat, lon, kind });
const E = (a, b, extra) => (extra ? [a, b, extra] : [a, b]);
const CANAL = { canal: true };

export const WORLD_NODES = [
  // Baltic, Gulf of Riga, Gulf of Bothnia, Kiel Canal
  N('irbe', 'Irbe Strait', 57.75, 21.75), N('riga_gulf', 'Gulf of Riga', 57.45, 23.6),
  N('klaipeda_appr', 'Klaipėda approach', 55.72, 20.85), N('aland_s', 'Åland Sea', 59.95, 19.45),
  N('bothnia_s', 'Bothnian Sea', 61.3, 19.6), N('bothnia_mid', 'Bothnian Sea north', 62.9, 20.3),
  N('kvarken', 'The Quark', 63.65, 21.0), N('bothnian_bay', 'Bothnian Bay', 64.9, 23.3),
  N('archipelago_s', 'South of the Archipelago Sea', 59.65, 22.0),
  N('brunsbuttel', 'Brunsbüttel (Kiel Canal west lock)', 53.885, 9.13, 'waypoint'), N('elbe_mouth_k', 'Elbe mouth', 53.89, 8.75, 'waypoint'),
  N('kiel_holtenau', 'Kiel-Holtenau (Kiel Canal east lock)', 54.37, 10.16, 'waypoint'),
  N('pomeranian_bay', 'Pomeranian Bay', 54.15, 14.3),
  // Norway, Barents Sea, White Sea, Greenland, Faroe
  N('halten', 'Off Haltenbanken', 64.2, 8.6), N('trondheim_appr', 'Trondheimsfjord approach', 63.75, 9.2),
  N('helgeland_w', 'Off Helgeland', 66.2, 11.0), N('vestfjord_mouth', 'Vestfjorden mouth', 67.55, 13.0),
  N('vestfjord', 'Vestfjorden', 68.1, 15.0), N('soroya_n', 'North of Sørøya', 71.0, 22.5),
  N('barents_s', 'Southern Barents Sea', 70.5, 40.0), N('white_sea_n', 'White Sea entrance', 67.6, 41.6),
  N('gorlo', 'Gorlo Strait', 66.3, 40.9), N('white_sea', 'White Sea', 65.4, 38.6),
  N('faroe_e', 'East of the Faroes', 61.9, -6.3), N('cape_farewell', 'Off Cape Farewell', 59.0, -44.0),
  N('davis_s', 'Southern Davis Strait', 63.5, -53.5),
  // British Isles, Biscay, Iberia, Atlantic islands
  N('clyde_s', 'Firth of Clyde', 55.3, -5.05), N('cork_appr', 'Cork approach', 51.7, -8.2),
  N('milford_appr', 'Milford Haven approach', 51.6, -5.3), N('loire_appr', 'Loire approach', 47.15, -2.5),
  N('gironde_appr', 'Gironde approach', 45.6, -1.4), N('cantabrian', 'Cantabrian Sea', 44.0, -5.0),
  N('bilbao_appr', 'Bilbao approach', 43.55, -3.1), N('cadiz_gulf', 'Gulf of Cádiz', 36.6, -7.0),
  N('azores', 'Azores', 37.4, -25.0), N('casablanca_appr', 'Casablanca approach', 33.8, -7.9),
  N('cabo_palos', 'Off Cabo de Palos', 37.5, -0.4), N('valencia_appr', 'Valencia approach', 39.3, 0.0),
  N('barcelona_appr', 'Barcelona approach', 41.2, 2.4), N('algiers_appr', 'Algiers approach', 37.0, 3.0),
  // Italy, Adriatic, Tunisia
  N('palermo_appr', 'Palermo approach', 38.45, 13.4), N('naples_appr', 'Gulf of Naples', 40.6, 14.05),
  N('messina_n', 'Strait of Messina north', 38.35, 15.6), N('messina_s', 'Strait of Messina south', 37.9, 15.45),
  N('taranto_appr', 'Gulf of Taranto', 40.0, 17.2), N('otranto', 'Strait of Otranto', 40.2, 18.9),
  N('adriatic_s', 'Southern Adriatic', 41.9, 17.6), N('adriatic_mid', 'Central Adriatic', 43.0, 15.0),
  N('adriatic_n', 'Northern Adriatic', 44.7, 13.1), N('venice_appr', 'Venice approach', 45.2, 12.6),
  N('trieste_gulf', 'Gulf of Trieste', 45.55, 13.45), N('kvarner', 'Kvarner', 44.95, 14.2),
  N('tunis_gulf', 'Gulf of Tunis', 37.15, 10.45),
  // Aegean, Levant, Bosporus, Black Sea
  N('thermaic', 'Thermaic Gulf', 40.2, 22.95), N('chios_w', 'West of Chios', 38.4, 25.6),
  N('izmir_appr', 'Gulf of İzmir', 38.65, 26.6), N('rhodes_s', 'South of Rhodes', 35.75, 28.0),
  N('cyprus_nw', 'North-west of Cyprus', 35.55, 32.0), N('cyprus_w', 'West of Cyprus', 34.9, 31.9),
  N('cyprus_s', 'South of Cyprus', 34.35, 33.2), N('levant', 'Levant basin', 33.0, 34.4),
  N('mersin_appr', 'Mersin approach', 36.5, 34.8), N('crete_s', 'South of Crete', 34.6, 25.0),
  N('bosporus_n', 'Bosporus north entrance', 41.3, 29.2), N('black_sea_sw', 'South-western Black Sea', 41.9, 29.4),
  N('black_sea_w', 'Western Black Sea', 43.5, 29.0), N('odesa_appr', 'Odesa approach', 46.25, 30.95),
  N('black_sea_c', 'Central Black Sea', 43.0, 33.0), N('crimea_s', 'South of Crimea', 43.9, 34.0),
  N('novo_appr', 'Novorossiysk approach', 44.55, 37.75),
  // West Africa
  N('cape_verde_n', 'North of São Vicente', 17.2, -24.6), N('sierra_leone_w', 'Off Sierra Leone', 8.3, -13.6),
  N('ivory_coast_s', 'Off Abidjan', 4.8, -4.0), N('tema_appr', 'Tema approach', 5.35, 0.1),
  N('benin_bight', 'Bight of Benin', 5.9, 2.4), N('niger_delta', 'Off the Niger delta', 3.6, 6.0),
  N('bioko_n', 'North of Bioko', 3.95, 8.55), N('cape_lopez', 'Off Cape Lopez', -0.8, 8.4),
  N('gabon_w', 'Off Libreville', 0.3, 9.1), N('congo_appr', 'Off Pointe-Noire', -5.0, 11.5),
  N('angola_n', 'Off Luanda', -8.6, 12.9), N('angola_s', 'Off Benguela', -13.0, 12.3),
  N('namibia_n', 'Off northern Namibia', -18.0, 11.0), N('walvis_appr', 'Walvis Bay approach', -22.9, 14.2),
  N('orange_w', 'Off the Orange River', -29.0, 15.5),
  // East Africa, Indian Ocean islands
  N('maputo_appr', 'Maputo approach', -25.95, 33.2), N('moz_s', 'Off Inhambane', -24.0, 36.2),
  N('beira_appr', 'Beira approach', -20.2, 35.4), N('dar_appr', 'Dar es Salaam approach', -6.75, 39.6),
  N('mogadishu_appr', 'Mogadishu approach', 2.0, 45.6), N('somalia_e', 'Off Somalia', 6.0, 50.0),
  N('guardafui', 'Off Cape Guardafui', 12.1, 51.8), N('madagascar_se', 'South-east of Madagascar', -25.6, 48.0),
  N('madagascar_e', 'East of Madagascar', -21.0, 49.4), N('toamasina_appr', 'Toamasina approach', -18.1, 49.7),
  N('mauritius', 'Off Mauritius', -20.0, 57.25), N('seychelles', 'Seychelles', -4.5, 55.75),
  N('maldives_w', 'West of the Maldives', 4.2, 73.2),
  // Red Sea, Arabia, Persian Gulf
  N('djibouti_appr', 'Djibouti approach', 11.75, 43.35), N('red_sea_c', 'Central Red Sea', 20.2, 38.6),
  N('tiran', 'Strait of Tiran', 27.95, 34.5), N('aqaba_gulf', 'Gulf of Aqaba', 28.8, 34.75),
  N('salalah_appr', 'Salalah approach', 16.75, 54.1), N('gulf_c', 'Central Persian Gulf', 26.6, 52.5),
  N('qatar_n', 'North of Qatar', 26.5, 51.6), N('doha_appr', 'Doha approach', 25.3, 51.85),
  N('bahrain_appr', 'Bahrain approach', 26.45, 50.95), N('gulf_nw', 'Northern Persian Gulf', 28.3, 50.0),
  N('kuwait_appr', 'Kuwait approach', 29.0, 48.6), N('shatt_appr', 'Khawr Abd Allah approach', 29.65, 48.75),
  N('kharg_appr', 'Kharg approach', 29.1, 50.1), N('abu_dhabi_appr', 'Abu Dhabi approach', 25.0, 54.3),
  // South Asia, Bay of Bengal
  N('karachi_appr', 'Karachi approach', 24.6, 66.75), N('kutch_appr', 'Gulf of Kutch approach', 22.5, 68.8),
  N('kochi_appr', 'Kochi approach', 9.9, 75.9), N('sri_lanka_e', 'East of Sri Lanka', 8.0, 82.2),
  N('chennai_appr', 'Chennai approach', 13.1, 80.6), N('vizag_appr', 'Visakhapatnam approach', 17.5, 83.6),
  N('paradip_appr', 'Paradip approach', 20.1, 87.0), N('sagar_appr', 'Sagar Roads approach', 21.1, 88.2),
  N('bengal_c', 'Central Bay of Bengal', 15.0, 88.0), N('bengal_ne', 'Off Chittagong', 21.6, 91.3),
  N('preparis', 'Preparis Channel', 14.9, 93.6), N('yangon_appr', 'Gulf of Martaban', 16.0, 96.2),
  N('six_degree', 'Six Degree Channel', 6.0, 94.5),
  // Malacca, Gulf of Thailand, Vietnam, Borneo, Philippines
  N('belawan_appr', 'Belawan approach', 3.95, 98.9), N('penang_appr', 'Penang approach', 5.3, 99.95),
  N('camau_se', 'South-east of Cà Mau', 7.6, 105.5), N('gulf_thailand', 'Gulf of Thailand', 9.5, 102.0),
  N('bight_bangkok', 'Bight of Bangkok', 12.6, 100.75), N('vung_tau_appr', 'Vũng Tàu approach', 10.1, 107.3),
  N('vietnam_c', 'Off central Vietnam', 15.5, 109.6), N('tonkin', 'Gulf of Tonkin', 19.5, 107.5),
  N('haiphong_appr', 'Haiphong approach', 20.5, 107.1), N('bintulu_appr', 'Bintulu approach', 3.5, 112.8),
  N('brunei_appr', 'Brunei Bay approach', 5.2, 114.8), N('kk_appr', 'Kota Kinabalu approach', 6.1, 115.8),
  N('balabac', 'Balabac Strait', 7.75, 116.9), N('sulu', 'Sulu Sea', 8.5, 120.0),
  N('bohol_sea', 'Bohol Sea', 9.2, 124.3),
  // Indonesia, Timor, Torres Strait, PNG
  N('java_sea_e', 'Eastern Java Sea', -5.5, 112.0), N('surabaya_appr', 'Surabaya west channel', -6.75, 112.65),
  N('lombok_n', 'Lombok Strait north', -8.1, 115.75), N('lombok_s', 'Lombok Strait south', -9.0, 115.8),
  N('makassar_s', 'Makassar Strait south', -4.0, 117.8), N('makassar_c', 'Makassar Strait', -1.5, 117.6),
  N('makassar_n', 'Makassar Strait north', 0.5, 118.8), N('celebes', 'Celebes Sea', 3.5, 121.5),
  N('mindanao_s', 'South of Mindanao', 5.0, 125.8), N('flores_sea', 'Flores Sea', -7.4, 121.0),
  N('banda', 'Banda Sea', -6.0, 127.0), N('sumba_s', 'South of Sumba', -11.0, 120.0), N('timor_sea', 'Timor Sea', -11.0, 127.0),
  N('darwin_appr', 'Darwin approach', -12.1, 130.4), N('arafura', 'Arafura Sea', -10.0, 135.0),
  N('torres_w', 'Torres Strait west', -10.6, 141.2), N('torres_e', 'Torres Strait east', -10.0, 143.6),
  N('moresby_appr', 'Port Moresby approach', -9.65, 146.95),
  // East Asia
  N('pearl_mouth', 'Pearl River mouth', 22.15, 113.8), N('taiwan_strait_s', 'Taiwan Strait south', 23.3, 118.6),
  N('taiwan_strait', 'Taiwan Strait', 24.5, 119.6), N('taiwan_strait_n', 'Taiwan Strait north', 25.8, 120.6),
  N('kaohsiung_appr', 'Kaohsiung approach', 22.45, 120.05), N('zhoushan_appr', 'Zhoushan approach', 29.9, 122.7),
  N('yellow_sea_s', 'Southern Yellow Sea', 33.0, 124.5), N('yellow_sea', 'Yellow Sea', 35.5, 123.5),
  N('qingdao_appr', 'Qingdao approach', 35.85, 120.6), N('shandong_e', 'Off Chengshan', 37.3, 123.0),
  N('bohai_strait', 'Bohai Strait', 38.45, 121.05), N('bohai', 'Bohai Sea', 38.7, 119.5),
  N('tianjin_appr', 'Tianjin approach', 38.95, 118.2), N('incheon_appr', 'Incheon approach', 37.15, 126.0),
  N('korea_strait_w', 'Western Korea Strait', 34.0, 127.6), N('gwangyang_appr', 'Gwangyang approach', 34.65, 127.85),
  N('genkai', 'Genkai Sea', 33.85, 130.1), N('japan_sea_sw', 'South-western Sea of Japan', 36.0, 131.5),
  N('japan_sea_c', 'Sea of Japan', 39.5, 135.0), N('sado_n', 'North of Sado', 38.6, 138.7),
  N('peter_great_bay', 'Peter the Great Gulf', 42.75, 132.2), N('japan_sea_n', 'Northern Sea of Japan', 44.3, 140.4),
  N('soya', 'La Pérouse Strait', 45.75, 142.0), N('aniva', 'Aniva Bay', 46.3, 142.75),
  N('okhotsk_s', 'Southern Sea of Okhotsk', 45.6, 145.0), N('okhotsk_c', 'Sea of Okhotsk', 50.0, 148.0),
  N('sakhalin_e', 'Off north-east Sakhalin', 51.5, 144.6), N('bussol', 'Bussol Strait', 46.6, 151.8),
  N('kii_channel', 'Kii Channel', 33.85, 134.95), N('osaka_bay', 'Osaka Bay', 34.45, 135.2),
  N('irago', 'Irago Channel', 34.45, 137.1), N('ise_bay', 'Ise Bay', 34.8, 136.8),
  N('boso_s', 'Off Nojimazaki', 34.75, 140.0), N('inubo', 'Off Inubōsaki', 35.7, 141.25),
  N('japan_ne', 'Off Sanriku', 38.5, 142.6), N('tsugaru_w', 'Tsugaru Strait west', 41.3, 139.8), N('tsugaru_e', 'Tsugaru Strait east', 41.5, 141.8),
  N('hokkaido_se', 'South-east of Hokkaido', 41.8, 144.5), N('tomakomai_appr', 'Tomakomai approach', 42.35, 141.7),
  N('kuril_e', 'East of the Kurils', 46.0, 153.5), N('kamchatka_se', 'Off Avacha Bay', 52.5, 159.3),
  N('pacific_nc', 'North Pacific', 45.0, 175.0),
  // Alaska, Pacific North America
  N('aleutian_w', 'South of the western Aleutians', 50.5, 178.0), N('aleutian_s', 'South of the Fox Islands', 52.6, -168.5),
  N('unimak_s', 'South of Unimak', 54.0, -164.5), N('dutch_appr', 'Unalaska Bay approach', 54.0, -166.4),
  N('alaska_pen_s', 'South of the Alaska Peninsula', 55.0, -158.0), N('kodiak_e', 'East of Kodiak', 57.5, -151.6),
  N('gulf_alaska', 'Gulf of Alaska', 58.0, -147.0), N('cook_inlet_s', 'Kennedy Entrance', 59.15, -151.9),
  N('cook_inlet', 'Cook Inlet', 60.4, -151.7), N('gulf_alaska_e', 'Eastern Gulf of Alaska', 57.0, -138.0),
  N('dixon_w', 'Dixon Entrance west', 54.3, -133.5), N('hecate_n', 'Northern Hecate Strait', 54.0, -130.9),
  N('hecate_s', 'Queen Charlotte Sound', 51.8, -129.8), N('vancouver_isl_w', 'Off Cape Scott', 50.6, -129.0),
  N('pacific_ne', 'North-east Pacific (great circle)', 47.0, -140.0), N('admiralty', 'Admiralty Inlet', 48.1, -122.65),
  N('sf_appr', 'San Francisco approach', 37.7, -122.85), N('mendocino_w', 'Off Cape Mendocino', 40.4, -125.0),
  N('sd_appr', 'San Diego approach', 32.6, -117.4), N('baja_w', 'Off Vizcaíno', 27.0, -116.0),
  N('manzanillo_appr', 'Manzanillo approach', 18.9, -104.6), N('lazaro_appr', 'Lázaro Cárdenas approach', 17.8, -102.3),
  N('quetzal_appr', 'Puerto Quetzal approach', 13.7, -90.9), N('nicoya_appr', 'Gulf of Nicoya approach', 9.5, -85.0),
  N('balboa_appr', 'Balboa approach', 8.75, -79.5),
  // Pacific South America, Magellan
  N('buenaventura_appr', 'Buenaventura approach', 3.8, -77.6), N('guayaquil_gulf', 'Gulf of Guayaquil', -3.0, -80.6),
  N('peru_n', 'Off northern Peru', -6.0, -81.6), N('callao_appr', 'Callao approach', -12.1, -77.4),
  N('peru_s', 'Off southern Peru', -16.5, -74.5), N('antofagasta_appr', 'Antofagasta approach', -23.6, -70.75),
  N('talcahuano_appr', 'Talcahuano approach', -36.55, -73.3), N('guafo', 'Boca del Guafo', -43.6, -74.8),
  N('corcovado', 'Gulf of Corcovado', -43.3, -73.4), N('ancud_gulf', 'Gulf of Ancud', -42.2, -73.0),
  N('magellan_e', 'Strait of Magellan east', -52.4, -68.2),
  N('magellan_c', 'Strait of Magellan', -52.95, -70.55), N('beagle_e', 'Beagle Channel east', -55.0, -66.8),
  N('ushuaia_appr', 'Beagle Channel off Ushuaia', -54.88, -68.1),
  // Atlantic South America
  N('montevideo_appr', 'Montevideo approach', -35.05, -56.0), N('mar_del_plata_appr', 'Mar del Plata approach', -38.1, -57.3),
  N('necochea_s', 'Off Necochea', -39.0, -59.0), N('bahia_blanca_appr', 'Bahía Blanca approach', -39.2, -61.6),
  N('valdes_e', 'East of Península Valdés', -42.6, -63.4), N('golfo_nuevo', 'Golfo Nuevo', -42.8, -64.7),
  N('patagonia_e', 'Off Patagonia', -48.0, -64.0), N('rio_grande_appr', 'Rio Grande approach', -32.3, -51.8),
  N('paranagua_appr', 'Paranaguá approach', -25.65, -48.1), N('ilha_grande_s', 'South of Ilha Grande', -23.3, -44.2),
  N('vitoria_appr', 'Vitória approach', -20.3, -40.0), N('sao_tome_e', 'Off Cabo de São Tomé', -22.3, -40.4), N('salvador_appr', 'Salvador approach', -13.1, -38.35),
  N('natal_e', 'Off Cape São Roque', -5.5, -34.8), N('fortaleza_n', 'Off Fortaleza', -3.2, -38.6),
  N('itaqui_appr', 'São Marcos Bay approach', -2.0, -44.2), N('para_mouth', 'Pará River mouth', -0.5, -48.0),
  N('amapa', 'Off Amapá', 3.0, -49.5), N('guiana', 'Off the Guianas', 7.5, -56.0),
  N('georgetown_appr', 'Georgetown approach', 7.0, -58.1),
  // Caribbean, Gulf of Mexico, US East coast, Canada
  N('tobago_n', 'North-west of Tobago', 11.6, -60.9), N('dragon_mouth', "Dragon's Mouth", 10.75, -61.75),
  N('antilles_e', 'East of the Windward Islands', 15.0, -59.5), N('anegada', 'Anegada Passage', 18.5, -63.8),
  N('pr_n', 'North of Puerto Rico', 18.7, -66.1), N('mona', 'Mona Passage', 18.3, -67.8),
  N('caucedo_appr', 'Caucedo approach', 18.3, -69.6), N('caribbean_e', 'Eastern Caribbean', 15.0, -67.0),
  N('caribbean_c', 'Central Caribbean', 15.5, -75.0), N('jamaica_s', 'South of Jamaica', 17.5, -76.8),
  N('windward_passage', 'Windward Passage', 20.0, -73.8), N('atlantic_bahamas', 'East of the Bahamas', 24.5, -72.0),
  N('cartagena_appr', 'Cartagena approach', 10.4, -75.8), N('curacao_n', 'North of Curaçao', 12.4, -69.0),
  N('pto_cabello_appr', 'Puerto Cabello approach', 10.7, -68.0), N('honduras_gulf', 'Gulf of Honduras', 16.0, -88.0),
  N('havana_appr', 'Mariel approach', 23.2, -82.75), N('freeport_appr', 'Freeport approach', 26.45, -78.85),
  N('corpus_appr', 'Corpus Christi approach', 27.7, -96.8), N('sw_pass', 'Southwest Pass approach', 28.8, -89.55),
  N('tampa_appr', 'Tampa Bay approach', 27.55, -83.0), N('tamaulipas', 'Off Tamaulipas', 24.0, -96.9),
  N('veracruz_appr', 'Veracruz approach', 19.3, -95.9), N('campeche', 'Bay of Campeche', 20.5, -93.0),
  N('campeche_n', 'North of the Campeche Bank', 23.0, -90.0), N('jacksonville_e', 'Off Jacksonville', 30.4, -80.8),
  N('savannah_appr', 'Savannah approach', 31.9, -80.6), N('charleston_appr', 'Charleston approach', 32.6, -79.6),
  N('chesapeake_mouth', 'Chesapeake Bay entrance', 36.95, -75.9), N('chesapeake_mid', 'Chesapeake Bay', 38.0, -76.2),
  N('cape_cod_e', 'East of Cape Cod', 42.0, -69.7), N('boston_appr', 'Boston approach', 42.35, -70.7),
  N('cape_breton_e', 'East of Cape Breton', 45.9, -59.0), N('cabot_strait', 'Cabot Strait', 47.3, -59.8),
  N('anticosti_s', 'South of Anticosti', 48.8, -63.5), N('gaspe_n', 'North of Gaspé', 49.3, -66.0),
  N('st_lawrence', 'St. Lawrence estuary', 48.8, -68.3), N('saguenay', 'Off the Saguenay', 48.05, -69.55),
  N('avalon_e', "St. John's approach", 47.5, -52.4),
  // Australia, New Zealand, Pacific islands
  N('perth_appr', 'Fremantle approach', -32.0, 115.5), N('shark_bay_w', 'West of Shark Bay', -26.0, 112.5),
  N('nw_cape', 'Off North West Cape', -21.6, 113.7), N('dampier_appr', 'Dampier approach', -20.3, 116.6),
  N('hedland_appr', 'Port Hedland approach', -19.9, 118.6), N('broome_w', 'Off Broome', -17.8, 120.5),
  N('browse', 'Browse Basin', -14.0, 123.0), N('kangaroo_s', 'South of Kangaroo Island', -36.3, 137.5),
  N('backstairs', 'Backstairs Passage', -35.72, 138.1), N('st_vincent_gulf', 'Gulf St Vincent', -35.2, 138.3),
  N('otway_s', 'South of Cape Otway', -39.0, 143.3), N('port_phillip_appr', 'Port Phillip approach', -38.45, 144.5),
  N('tasmania_ne', 'North-east of Tasmania', -40.8, 148.8), N('tasmania_se', 'South-east of Tasmania', -43.4, 147.9),
  N('storm_bay', 'Storm Bay', -43.15, 147.55), N('newcastle_appr', 'Newcastle approach', -32.95, 152.0),
  N('port_macquarie_e', 'Off Port Macquarie', -31.5, 153.3), N('brisbane_appr', 'Moreton Bay north channel', -27.0, 153.4),
  N('fraser_e', 'East of Fraser Island', -25.0, 153.8), N('sandy_cape_n', 'North of Breaksea Spit', -24.3, 153.4),
  N('gladstone_appr', 'Gladstone approach', -23.7, 151.6), N('hay_point_appr', 'Hay Point approach', -21.1, 149.6),
  N('cape_egmont_w', 'West of Cape Egmont', -39.3, 173.0), N('cook_strait', 'Cook Strait', -41.4, 174.55),
  N('mercury_e', 'East of the Mercury Islands', -36.6, 176.2), N('bay_plenty', 'Bay of Plenty', -37.4, 176.4),
  N('east_cape', 'Off East Cape', -37.5, 178.9), N('hawke_bay', 'Off Hawke Bay', -39.6, 177.9),
  N('palliser_s', 'South of Cape Palliser', -41.8, 175.4), N('kaikoura', 'Off Kaikōura', -42.5, 173.95),
  N('banks_pen', 'Off Banks Peninsula', -43.7, 173.2),
  N('fiji_s', 'South of Viti Levu', -18.4, 178.4), N('noumea_appr', 'Nouméa approach', -22.6, 166.35),
  N('tahiti_n', 'North of Tahiti', -17.4, -149.6), N('samoa_n', 'North of Upolu', -13.6, -171.8),
  N('guam_w', 'West of Guam', 13.45, 144.45),
  // Harbour approaches where the straight harbour link clips the raster (fjords, estuaries, archipelagos)
  N('brest_roads', "Brest roads (Goulet)", 48.352, -4.546, 'waypoint'),
  N('reykjavik_faxa', "Faxaflói", 64.092, -22.791, 'waypoint'),
  N('tokyo_bay', "Tokyo Bay", 35.492, 139.8, 'waypoint'),
  N('vancouver_burrard', "English Bay (Burrard Inlet approach)", 49.281, -123.263, 'waypoint'),
  N('neva_bay', "Neva Bay approach", 59.993, 29.794, 'waypoint'),
  N('stockholm_arch', "Stockholm archipelago (Sandhamn)", 59.424, 18.442, 'waypoint'),
  N('luga_bay', "Luga Bay", 59.877, 28.485, 'waypoint'),
  N('ofotfjord', "Ofotfjorden", 68.428, 16.519, 'waypoint'),
  N('tromso_sound', "Tromsøysundet approach", 69.697, 19.038, 'waypoint'),
  N('hammerfest_appr', "Hammerfest approach", 70.878, 23.4, 'waypoint'),
  N('bokfjord', "Bøkfjorden", 69.845, 30.142, 'waypoint'),
  N('clyde_tail', "Tail of the Bank approach", 55.967, -4.91, 'waypoint'),
  N('thessaloniki_roads', "Thessaloniki roads", 40.548, 22.831, 'waypoint'),
  N('khawr_abd_allah', "Khawr Abd Allah", 29.99, 48.185, 'waypoint'),
  N('bandar_abbas_roads', "Bandar Abbas roads", 26.971, 56.264, 'waypoint'),
  N('cebu_s', "Cebu Strait south", 9.768, 123.738, 'waypoint'),
  N('dili_appr', "Dili approach", -8.297, 125.491, 'waypoint'),
  N('ningbo_appr', "Ningbo (Xiazhi Men) approach", 29.837, 122.242, 'waypoint'),
  N('cook_inlet_n', "Upper Cook Inlet", 60.855, -151.22, 'waypoint'),
  N('puget_n', "Puget Sound north", 47.761, -122.424, 'waypoint'),
  N('quebec_appr', "Off Île aux Coudres", 47.112, -70.723, 'waypoint'),
  N('para_river', "Pará River off Vila do Conde", -1.211, -48.5, 'waypoint'),
  N('chesapeake_c', 'Chesapeake Bay (Smith Point)', 38.45, -76.38), N('chesapeake_n', 'Chesapeake Bay (Bay Bridge)', 39.05, -76.33), N('chesapeake_b', 'Chesapeake Bay (Sharps Island)', 38.75, -76.4),
  N('kola_inner', 'Kola Bay off Murmansk', 69.0, 33.07, 'waypoint'), N('trondheim_inner', 'Trondheimsfjord off Trondheim', 63.47, 10.35, 'waypoint'),
];

export const WORLD_EDGES = [
  // Baltic, Bothnia, Kiel Canal
  E('baltic_c', 'irbe'), E('irbe', 'riga_gulf'), E('rozewie_n', 'klaipeda_appr'), E('baltic_c', 'klaipeda_appr'),
  E('stockholm_appr', 'aland_s'), E('aland_s', 'bothnia_s'), E('bothnia_s', 'bothnia_mid'), E('bothnia_mid', 'kvarken'),
  E('kvarken', 'bothnian_bay'), E('hiiumaa_n', 'archipelago_s'), E('aland_s', 'archipelago_s'),
  E('elbe_appr', 'elbe_mouth_k'), E('elbe_mouth_k', 'brunsbuttel'), E('brunsbuttel', 'kiel_holtenau', CANAL), E('kiel_holtenau', 'kiel_appr'),
  E('bornholm', 'pomeranian_bay'),
  // Norway, Barents, White Sea, Greenland, Faroe
  E('stad', 'halten'), E('halten', 'trondheim_appr'), E('halten', 'norway_n'), E('halten', 'helgeland_w'),
  E('helgeland_w', 'vestfjord_mouth'), E('norway_n', 'helgeland_w'), E('vestfjord_mouth', 'vestfjord'), E('vestfjord_mouth', 'lofoten_w'),
  E('tromso_w', 'soroya_n'), E('soroya_n', 'north_cape'), E('varanger_n', 'barents_s'), E('murmansk_appr', 'barents_s'),
  E('barents_s', 'white_sea_n'), E('white_sea_n', 'gorlo'), E('gorlo', 'white_sea'),
  E('faroe', 'faroe_e'), E('shetland_n', 'faroe_e'), E('iceland_s', 'cape_farewell'), E('atlantic_n', 'cape_farewell'),
  E('cape_farewell', 'davis_s'), E('grand_banks_s', 'cape_farewell'),
  // British Isles, Biscay, Iberia, islands, Morocco, Algeria
  E('north_channel', 'clyde_s'), E('fastnet', 'cork_appr'), E('stgeorges', 'cork_appr'), E('stgeorges', 'milford_appr'),
  E('biscay', 'loire_appr'), E('ushant', 'loire_appr'), E('biscay', 'gironde_appr'), E('loire_appr', 'gironde_appr'),
  E('biscay', 'cantabrian'), E('cantabrian', 'bilbao_appr'), E('gironde_appr', 'bilbao_appr'), E('cantabrian', 'finisterre'),
  E('st_vincent', 'cadiz_gulf'), E('cadiz_gulf', 'gibraltar_strait'), E('atlantic_n', 'azores'), E('azores', 'st_vincent'),
  E('azores', 'canaries'), E('st_vincent', 'casablanca_appr'), E('canaries', 'casablanca_appr'), E('gibraltar_strait', 'casablanca_appr'),
  E('alboran', 'cabo_palos'), E('cabo_palos', 'med_w'), E('cabo_palos', 'valencia_appr'), E('med_w', 'valencia_appr'),
  E('valencia_appr', 'barcelona_appr'), E('barcelona_appr', 'lion'), E('med_w', 'barcelona_appr'),
  E('med_w', 'algiers_appr'), E('alboran', 'algiers_appr'), E('algiers_appr', 'sardinia_s'),
  // Italy, Adriatic, Tunisia
  E('tyrrhenian', 'palermo_appr'), E('sicily_w', 'palermo_appr'), E('tyrrhenian', 'naples_appr'),
  E('tyrrhenian', 'messina_n'), E('palermo_appr', 'messina_n'), E('messina_n', 'messina_s', CANAL), E('messina_s', 'malta'), E('messina_s', 'ionian'),
  E('ionian', 'taranto_appr'), E('ionian', 'otranto'), E('taranto_appr', 'otranto'), E('otranto', 'adriatic_s'),
  E('adriatic_s', 'adriatic_mid'), E('adriatic_mid', 'adriatic_n'), E('adriatic_n', 'venice_appr'), E('adriatic_n', 'trieste_gulf'),
  E('adriatic_n', 'kvarner'), E('venice_appr', 'trieste_gulf'),
  E('sicily_w', 'tunis_gulf'), E('sardinia_s', 'tunis_gulf'), E('malta', 'tunis_gulf'),
  // Aegean, Levant, Black Sea
  E('aegean_n', 'thermaic'), E('aegean_n', 'chios_w'), E('kafireas_e', 'chios_w'), E('chios_w', 'izmir_appr'),
  E('med_e', 'rhodes_s'), E('rhodes_s', 'cyprus_nw'), E('cyprus_nw', 'mersin_appr'), E('cyprus_nw', 'cyprus_w'),
  E('med_e', 'cyprus_w'), E('cyprus_w', 'cyprus_s'), E('cyprus_s', 'levant'), E('levant', 'port_said'), E('levant', 'delta_n'),
  E('crete_w', 'crete_s'), E('crete_s', 'med_e'), E('rhodes_s', 'crete_s'),
  E('marmara', 'bosporus_n', CANAL), E('bosporus_n', 'black_sea_sw'), E('black_sea_sw', 'black_sea_w'), E('black_sea_w', 'odesa_appr'),
  E('black_sea_sw', 'black_sea_c'), E('black_sea_w', 'black_sea_c'), E('black_sea_c', 'crimea_s'), E('crimea_s', 'novo_appr'),
  E('black_sea_c', 'novo_appr'), E('odesa_appr', 'crimea_s'),
  // West Africa
  E('cape_verde', 'cape_verde_n'), E('canaries', 'cape_verde_n'), E('cap_blanc', 'cape_verde_n'),
  E('dakar_appr', 'sierra_leone_w'), E('sierra_leone_w', 'liberia_w'), E('liberia_w', 'ivory_coast_s'), E('ivory_coast_s', 'tema_appr'),
  E('gulf_guinea', 'ivory_coast_s'), E('gulf_guinea', 'tema_appr'), E('tema_appr', 'benin_bight'), E('benin_bight', 'niger_delta'),
  E('niger_delta', 'bioko_n'), E('niger_delta', 'cape_lopez'), E('gulf_guinea', 'cape_lopez'), E('cape_lopez', 'gabon_w'),
  E('cape_lopez', 'congo_appr'), E('congo_appr', 'angola_n'), E('angola_n', 'angola_s'), E('angola_s', 'namibia_n'),
  E('namibia_n', 'walvis_appr'), E('walvis_appr', 'orange_w'), E('orange_w', 'cape_town_appr'), E('namibia_n', 'atlantic_s'),
  E('orange_w', 'cape_point'),
  // East Africa, Indian Ocean
  E('durban_e', 'maputo_appr'), E('maputo_appr', 'moz_s'), E('moz_s', 'beira_appr'), E('beira_appr', 'moz_channel'), E('moz_s', 'moz_channel'),
  E('comoros_e', 'dar_appr'), E('dar_appr', 'mombasa_appr'), E('mombasa_appr', 'mogadishu_appr'), E('mogadishu_appr', 'somalia_e'),
  E('somalia_e', 'guardafui'), E('guardafui', 'gulf_aden'), E('madagascar_s', 'madagascar_se'), E('madagascar_se', 'madagascar_e'),
  E('madagascar_e', 'toamasina_appr'), E('madagascar_e', 'mauritius'), E('mauritius', 'seychelles'), E('seychelles', 'mombasa_appr'),
  E('seychelles', 'arabian_sea'), E('seychelles', 'maldives_w'), E('maldives_w', 'cape_comorin'), E('maldives_w', 'dondra'),
  E('somalia_e', 'seychelles'), E('mauritius', 'indian_ocean_e'),
  // Red Sea, Arabia, Persian Gulf
  E('aden_w', 'djibouti_appr'), E('bab_el_mandeb', 'djibouti_appr'), E('red_sea_s', 'red_sea_c'), E('red_sea_c', 'red_sea_n'),
  E('red_sea_n', 'tiran'), E('tiran', 'aqaba_gulf'), E('arabian_sea', 'salalah_appr'), E('gulf_aden', 'salalah_appr'), E('salalah_appr', 'ras_al_hadd'),
  E('gulf_s', 'abu_dhabi_appr'), E('gulf_s', 'gulf_c'), E('hormuz_w', 'gulf_c'), E('gulf_c', 'qatar_n'), E('gulf_c', 'doha_appr'),
  E('qatar_n', 'bahrain_appr'), E('gulf_c', 'gulf_nw'), E('gulf_nw', 'bahrain_appr'), E('gulf_nw', 'kuwait_appr'),
  E('kuwait_appr', 'shatt_appr'), E('gulf_nw', 'kharg_appr'), E('gulf_nw', 'shatt_appr'),
  // South Asia, Bay of Bengal
  E('ras_al_hadd', 'karachi_appr'), E('arabian_sea', 'karachi_appr'), E('karachi_appr', 'kutch_appr'), E('kutch_appr', 'mumbai_appr'),
  E('goa_w', 'kochi_appr'), E('kochi_appr', 'cape_comorin'), E('dondra', 'sri_lanka_e'), E('sri_lanka_e', 'chennai_appr'),
  E('chennai_appr', 'vizag_appr'), E('vizag_appr', 'paradip_appr'), E('paradip_appr', 'sagar_appr'), E('sri_lanka_e', 'bengal_c'),
  E('bengal_c', 'vizag_appr'), E('bengal_c', 'paradip_appr'), E('bengal_c', 'bengal_ne'), E('sagar_appr', 'bengal_ne'),
  E('bengal_c', 'preparis'), E('preparis', 'yangon_appr'), E('dondra', 'six_degree'), E('six_degree', 'malacca_n'), E('bengal_c', 'six_degree'),
  // Malacca, Thailand, Vietnam, Borneo, Philippines
  E('malacca_n', 'belawan_appr'), E('belawan_appr', 'malacca_s'), E('malacca_n', 'penang_appr'), E('penang_appr', 'malacca_s'),
  E('scs_s', 'camau_se'), E('camau_se', 'gulf_thailand'), E('gulf_thailand', 'bight_bangkok'), E('horsburgh', 'camau_se'),
  E('scs_s', 'vung_tau_appr'), E('scs_mid', 'vung_tau_appr'), E('scs_mid', 'vietnam_c'), E('vietnam_c', 'tonkin'),
  E('tonkin', 'haiphong_appr'), E('vietnam_c', 'hk_appr'), E('scs_s', 'bintulu_appr'), E('bintulu_appr', 'brunei_appr'),
  E('brunei_appr', 'kk_appr'), E('kk_appr', 'balabac'), E('balabac', 'sulu'), E('sulu', 'bohol_sea'), E('scs_mid', 'kk_appr'),
  // Indonesia, Timor, Torres, PNG
  E('java_sea', 'java_sea_e'), E('java_sea_e', 'surabaya_appr'), E('java_sea_e', 'lombok_n'), E('lombok_n', 'lombok_s'),
  E('lombok_s', 'indian_ocean_e'), E('java_sea_e', 'makassar_s'), E('makassar_s', 'makassar_c'), E('makassar_c', 'makassar_n'),
  E('makassar_n', 'celebes'), E('celebes', 'mindanao_s'), E('celebes', 'sulu'), E('lombok_n', 'flores_sea'), E('makassar_s', 'flores_sea'),
  E('flores_sea', 'banda'), E('lombok_s', 'sumba_s'), E('sumba_s', 'timor_sea'),
  E('timor_sea', 'darwin_appr'), E('timor_sea', 'browse'), E('timor_sea', 'arafura'),
  E('arafura', 'torres_w'), E('torres_w', 'torres_e', CANAL), E('torres_e', 'moresby_appr'), E('coral_sea', 'moresby_appr'),
  E('indian_ocean_e', 'sumba_s'),
  // East Asia
  E('hk_appr', 'pearl_mouth'), E('hk_appr', 'taiwan_strait_s'), E('taiwan_strait_s', 'taiwan_strait'), E('taiwan_strait', 'taiwan_strait_n'),
  E('taiwan_strait_n', 'east_china_sea'), E('taiwan_strait_n', 'zhoushan_appr'), E('zhoushan_appr', 'shanghai_appr'),
  E('luzon_strait', 'kaohsiung_appr'), E('taiwan_strait_s', 'kaohsiung_appr'), E('east_china_sea', 'zhoushan_appr'),
  E('east_china_sea', 'yellow_sea_s'), E('shanghai_appr', 'yellow_sea_s'), E('yellow_sea_s', 'yellow_sea'), E('yellow_sea', 'qingdao_appr'),
  E('yellow_sea', 'shandong_e'), E('shandong_e', 'bohai_strait'), E('bohai_strait', 'bohai'), E('bohai', 'tianjin_appr'),
  E('yellow_sea', 'incheon_appr'), E('yellow_sea_s', 'korea_strait_w'), E('korea_strait_w', 'gwangyang_appr'), E('korea_strait_w', 'busan_appr'),
  E('korea_strait_w', 'goto'), E('busan_appr', 'genkai'), E('genkai', 'japan_sea_sw'), E('busan_appr', 'japan_sea_sw'),
  E('japan_sea_sw', 'japan_sea_c'), E('japan_sea_c', 'sado_n'), E('japan_sea_c', 'peter_great_bay'), E('japan_sea_c', 'japan_sea_n'),
  E('japan_sea_n', 'soya'), E('soya', 'aniva'), E('soya', 'okhotsk_s'), E('okhotsk_s', 'okhotsk_c'), E('okhotsk_c', 'sakhalin_e'),
  E('okhotsk_c', 'bussol'), E('bussol', 'kuril_e'), E('japan_sea_c', 'tsugaru_w'), E('tsugaru_w', 'tsugaru_e'),
  E('kii', 'kii_channel'), E('kii_channel', 'osaka_bay'), E('kii', 'irago'), E('irago', 'ise_bay'),
  E('tokyo_appr', 'boso_s'), E('izu_s', 'boso_s'), E('boso_s', 'inubo'), E('inubo', 'japan_ne'), E('japan_ne', 'tsugaru_e'),
  E('japan_ne', 'hokkaido_se'), E('tsugaru_e', 'tomakomai_appr'), E('hokkaido_se', 'tomakomai_appr'), E('hokkaido_se', 'kuril_e'),
  E('kuril_e', 'kamchatka_se'), E('hokkaido_se', 'pacific_nc'), E('kamchatka_se', 'aleutian_w'), E('pacific_nc', 'aleutian_w'),
  E('pacific_nw', 'japan_ne'), E('pacific_nc', 'pacific_mid'),
  // Alaska, Pacific North America
  E('aleutian_w', 'aleutian_s'), E('pacific_nc', 'aleutian_s'), E('dutch_appr', 'unimak_s'),
  E('aleutian_s', 'unimak_s'), E('unimak_s', 'alaska_pen_s'), E('alaska_pen_s', 'kodiak_e'), E('kodiak_e', 'gulf_alaska'),
  E('kodiak_e', 'cook_inlet_s'), E('gulf_alaska', 'cook_inlet_s'), E('cook_inlet_s', 'cook_inlet'), E('gulf_alaska', 'gulf_alaska_e'),
  E('gulf_alaska_e', 'dixon_w'), E('dixon_w', 'hecate_n'), E('hecate_n', 'hecate_s'), E('hecate_s', 'vancouver_isl_w'),
  E('vancouver_isl_w', 'juan_de_fuca'), E('pacific_nc', 'pacific_ne'), E('pacific_ne', 'juan_de_fuca'), E('pacific_ne', 'gulf_alaska_e'),
  E('pacific_ne', 'mendocino_w'), E('jdf_e', 'admiralty'), E('haro_s', 'admiralty'),
  E('juan_de_fuca', 'mendocino_w'), E('mendocino_w', 'sf_appr'), E('pacific_e', 'sf_appr'), E('la_appr', 'sd_appr'),
  E('sd_appr', 'baja_w'), E('pacific_e', 'baja_w'), E('baja_w', 'baja_s'), E('baja_s', 'manzanillo_appr'),
  E('manzanillo_appr', 'lazaro_appr'), E('lazaro_appr', 'tehuantepec'), E('tehuantepec', 'quetzal_appr'), E('quetzal_appr', 'nicoya_appr'),
  E('cocos', 'nicoya_appr'), E('nicoya_appr', 'panama_pac'), E('panama_pac', 'balboa_appr'), E('balboa_appr', 'colon_appr', CANAL),
  // Pacific South America, Magellan
  E('panama_pac', 'buenaventura_appr'), E('buenaventura_appr', 'galapagos_e'), E('galapagos_e', 'guayaquil_gulf'), E('guayaquil_gulf', 'peru_n'), E('peru_n', 'callao_appr'), E('callao_appr', 'peru_s'),
  E('peru_s', 'antofagasta_appr'), E('antofagasta_appr', 'valparaiso_appr'), E('pacific_se', 'callao_appr'), E('pacific_se', 'antofagasta_appr'),
  E('valparaiso_appr', 'talcahuano_appr'), E('talcahuano_appr', 'chile_s'), E('chile_s', 'guafo'), E('guafo', 'corcovado'),
  E('corcovado', 'ancud_gulf'), E('staten_e', 'magellan_e'), E('falklands_e', 'magellan_e'), E('magellan_e', 'magellan_c', CANAL),
  E('staten_e', 'beagle_e'), E('cape_horn', 'beagle_e'), E('beagle_e', 'ushuaia_appr', CANAL),
  // Atlantic South America
  E('rio_plata', 'montevideo_appr'), E('rio_plata', 'mar_del_plata_appr'), E('mar_del_plata_appr', 'necochea_s'),
  E('necochea_s', 'bahia_blanca_appr'), E('bahia_blanca_appr', 'valdes_e'), E('necochea_s', 'valdes_e'), E('valdes_e', 'golfo_nuevo'),
  E('valdes_e', 'patagonia_e'), E('patagonia_e', 'magellan_e'), E('patagonia_e', 'falklands_e'), E('patagonia_e', 'staten_e'),
  E('rio_grande_s', 'rio_grande_appr'), E('santa_catarina_e', 'paranagua_appr'), E('santos_appr', 'paranagua_appr'),
  E('santos_appr', 'ilha_grande_s'), E('rio_appr', 'ilha_grande_s'), E('abrolhos_e', 'vitoria_appr'), E('rio_appr', 'sao_tome_e'), E('sao_tome_e', 'vitoria_appr'), E('sao_tome_e', 'abrolhos_e'),
  E('abrolhos_e', 'salvador_appr'), E('recife_e', 'salvador_appr'), E('recife_e', 'natal_e'), E('natal_e', 'fortaleza_n'),
  E('fortaleza_n', 'itaqui_appr'), E('itaqui_appr', 'para_mouth'), E('para_mouth', 'amapa'), E('amapa', 'guiana'),
  E('guiana', 'georgetown_appr'), E('guiana', 'tobago_n'), E('atlantic_mid', 'natal_e'), E('atlantic_mid', 'guiana'),
  // Caribbean, Gulf of Mexico, North America east
  E('tobago_n', 'dragon_mouth'), E('caribbean_e', 'dragon_mouth'), E('atlantic_mid', 'antilles_e'), E('tobago_n', 'antilles_e'),
  E('antilles_e', 'anegada'), E('hatteras', 'anegada'), E('atlantic_mid', 'anegada'), E('anegada', 'caribbean_e'), E('anegada', 'pr_n'),
  E('pr_n', 'mona'), E('mona', 'caucedo_appr'), E('mona', 'caribbean_c'), E('caucedo_appr', 'caribbean_e'), E('caribbean_e', 'caribbean_c'),
  E('caribbean_c', 'jamaica_s'), E('windward_passage', 'jamaica_s'), E('windward_passage', 'atlantic_bahamas'), E('atlantic_bahamas', 'hatteras'),
  E('atlantic_bahamas', 'pr_n'), E('caribbean_c', 'caribbean_w'), E('caribbean_w', 'cartagena_appr'), E('caribbean_c', 'cartagena_appr'),
  E('caribbean_e', 'curacao_n'), E('curacao_n', 'pto_cabello_appr'), E('caribbean_e', 'antilles_e'), E('yucatan', 'honduras_gulf'),
  E('jamaica_s', 'yucatan'), E('tortugas_s', 'havana_appr'), E('florida_strait', 'havana_appr'), E('florida_e', 'freeport_appr'),
  E('galveston_appr', 'corpus_appr'), E('gulf_mexico', 'sw_pass'), E('gulf_mexico', 'tampa_appr'), E('tortugas_s', 'tampa_appr'),
  E('corpus_appr', 'tamaulipas'), E('tamaulipas', 'veracruz_appr'), E('veracruz_appr', 'campeche'), E('campeche', 'campeche_n'),
  E('campeche_n', 'yucatan'), E('campeche_n', 'gulf_mexico'), E('gulf_mexico', 'tamaulipas'),
  E('florida_e', 'jacksonville_e'), E('jacksonville_e', 'savannah_appr'), E('savannah_appr', 'charleston_appr'), E('charleston_appr', 'hatteras'),
  E('hatteras', 'chesapeake_mouth'), E('chesapeake_mouth', 'chesapeake_mid'), E('nyc_appr', 'chesapeake_mouth'),
  E('nantucket_s', 'cape_cod_e'), E('cape_cod_e', 'boston_appr'), E('cape_cod_e', 'sable_s'),
  E('sable_s', 'cape_breton_e'), E('cape_breton_e', 'cabot_strait'), E('cabot_strait', 'anticosti_s'), E('anticosti_s', 'gaspe_n'),
  E('gaspe_n', 'st_lawrence'), E('st_lawrence', 'saguenay'), E('grand_banks_s', 'avalon_e'), 
  // Australia, New Zealand, Pacific islands
  E('leeuwin', 'perth_appr'), E('perth_appr', 'shark_bay_w'), E('shark_bay_w', 'nw_cape'), E('nw_cape', 'dampier_appr'),
  E('dampier_appr', 'hedland_appr'), E('hedland_appr', 'broome_w'), E('broome_w', 'browse'), E('indian_ocean_e', 'nw_cape'),
  E('indian_ocean_e', 'shark_bay_w'), E('great_bight', 'kangaroo_s'), E('kangaroo_s', 'backstairs'), E('backstairs', 'st_vincent_gulf'),
  E('great_bight', 'otway_s'), E('kangaroo_s', 'otway_s'), E('otway_s', 'port_phillip_appr'), E('otway_s', 'bass_strait'),
  E('bass_strait', 'port_phillip_appr'), E('gabo', 'tasmania_ne'), E('bass_strait', 'tasmania_ne'), E('tasmania_ne', 'tasmania_se'),
  E('tasmania_se', 'storm_bay'), E('tasman', 'newcastle_appr'), E('newcastle_appr', 'port_macquarie_e'), E('port_macquarie_e', 'brisbane_appr'),
  E('brisbane_appr', 'fraser_e'), E('fraser_e', 'sandy_cape_n'), E('sandy_cape_n', 'gladstone_appr'), E('gladstone_appr', 'hay_point_appr'),
  E('coral_sea', 'fraser_e'), E('coral_sea', 'sandy_cape_n'), E('tasman_mid', 'cape_egmont_w'), E('cape_egmont_w', 'cook_strait'),
  E('northland_e', 'mercury_e'), E('hauraki', 'mercury_e'), E('mercury_e', 'bay_plenty'), E('bay_plenty', 'east_cape'),
  E('east_cape', 'hawke_bay'), E('hawke_bay', 'palliser_s'), E('palliser_s', 'cook_strait'), E('cook_strait', 'kaikoura'),
  E('kaikoura', 'banks_pen'), E('solomon_e', 'fiji_s'), E('fiji_s', 'samoa_n'), E('polynesia', 'samoa_n'), E('samoa_n', 'tahiti_n'),
  E('tahiti_n', 'hawaii_s'), E('tahiti_n', 'pacific_se'), E('coral_sea', 'noumea_appr'), E('tasman_mid', 'noumea_appr'),
  E('fiji_s', 'noumea_appr'), E('guam_w', 'luzon_strait'), E('guam_w', 'pacific_nw'), E('guam_w', 'solomon_e'), E('east_cape', 'fiji_s'),
  // Harbour approaches
  E('brest_roads', 'brest_appr'),
  E('reykjavik_faxa', 'iceland_s'),
  E('tokyo_bay', 'tokyo_appr'),
  E('vancouver_burrard', 'georgia_mid'),
  E('neva_bay', 'petersburg_appr'),
  E('stockholm_arch', 'stockholm_appr'),
  E('luga_bay', 'petersburg_appr'),
  E('ofotfjord', 'vestfjord'),
  E('tromso_sound', 'soroya_n'),
  E('hammerfest_appr', 'soroya_n'),
  E('bokfjord', 'barents_s'),
  E('clyde_tail', 'clyde_s'),
  E('thessaloniki_roads', 'thermaic'),
  E('khawr_abd_allah', 'shatt_appr'),
  E('bandar_abbas_roads', 'hormuz_w'),
  E('cebu_s', 'bohol_sea'),
  E('dili_appr', 'banda'),
  E('ningbo_appr', 'zhoushan_appr'),
  E('cook_inlet_n', 'cook_inlet'),
  E('puget_n', 'admiralty'),
  E('quebec_appr', 'saguenay'),
  E('para_river', 'para_mouth'),
  E('chesapeake_mid', 'chesapeake_c'), E('chesapeake_c', 'chesapeake_b'), E('chesapeake_b', 'chesapeake_n'),
  // fjords the 5 km raster closes: Kola Bay (Murmansk) and Trondheimsfjord
  E('murmansk_appr', 'kola_inner', CANAL), E('trondheim_appr', 'trondheim_inner', CANAL),
];

// Edges (from server/lanes.js or above) whose straight line clips land on the raster, split at one open-water waypoint
// [a, b, lat, lon]: the edge a–b is replaced by a–via–b (found by scanning offsets around the edge, both halves checked).
const VIAS = [
  ['fair_isle', 'lerwick_appr', 59.81, -1.28],
  ['malin', 'irish_w', 54.67, -9.55],
  ['viking_lane', 'faroe', 61.02, -2.35],
  ['egersund', 'stavanger_appr', 58.65, 5.40],
  ['great_belt', 'langeland_s', 55.21, 10.95],
  ['falsterbo_s', 'gedser', 54.85, 12.50],
  ['med_w', 'lion', 40.61, 3.15],
  ['ligurian', 'tyrrhenian', 42.68, 9.71],
  ['sounion_e', 'kafireas_e', 37.88, 24.48],
  ['suez_gulf', 'red_sea_n', 27.37, 34.02],
  ['dakar_appr', 'liberia_w', 9.04, -15.41],
  ['horsburgh', 'scs_s', 3.18, 105.78],
  ['hawaii_nw', 'kaena_w', 22.84, -159.89],
  ['polynesia', 'northland_e', -30.13, 178.36],
  ['jdf_e', 'haro_s', 48.28, -123.60],
  ['iceland_s', 'norway_n', 63.41, -7.06],
  ['irbe', 'riga_gulf', 57.71, 22.73],
  ['bornholm', 'pomeranian_bay', 54.91, 13.93],
  ['white_sea_n', 'gorlo', 66.94, 41.38],
  ['faroe', 'faroe_e', 61.57, -6.39],
  ['cape_farewell', 'davis_s', 61.08, -49.00],
  ['ushant', 'loire_appr', 47.74, -4.16],
  ['cantabrian', 'finisterre', 43.86, -7.48],
  ['gibraltar_strait', 'casablanca_appr', 35.19, -7.18],
  ['cabo_palos', 'valencia_appr', 38.32, 0.37],
  ['med_w', 'barcelona_appr', 39.80, 2.21],
  ['sicily_w', 'palermo_appr', 38.07, 12.56],
  ['messina_s', 'malta', 36.94, 15.29],
  ['taranto_appr', 'otranto', 39.68, 18.14],
  ['adriatic_n', 'kvarner', 44.72, 13.70],
  ['malta', 'tunis_gulf', 36.72, 12.80],
  ['aegean_n', 'thermaic', 39.76, 23.87],
  ['chios_w', 'izmir_appr', 38.71, 26.02],
  ['rhodes_s', 'crete_s', 35.11, 26.53],
  ['cape_verde', 'cape_verde_n', 16.17, -23.21],
  ['dakar_appr', 'sierra_leone_w', 11.11, -16.25],
  ['liberia_w', 'ivory_coast_s', 4.28, -7.99],
  ['ivory_coast_s', 'tema_appr', 4.73, -1.90],
  ['somalia_e', 'guardafui', 9.01, 51.05],
  ['bab_el_mandeb', 'djibouti_appr', 12.10, 43.46],
  ['salalah_appr', 'ras_al_hadd', 18.08, 58.66],
  ['hormuz_w', 'gulf_c', 26.45, 54.25],
  ['kutch_appr', 'mumbai_appr', 20.37, 70.23],
  ['dondra', 'sri_lanka_e', 6.53, 81.81],
  ['bengal_c', 'six_degree', 10.14, 90.77],
  ['bintulu_appr', 'brunei_appr', 4.39, 113.76],
  ['java_sea_e', 'lombok_n', -6.76, 113.90],
  ['makassar_s', 'flores_sea', -5.81, 119.28],
  ['tsugaru_w', 'tsugaru_e', 41.51, 140.78],
  ['kii_channel', 'osaka_bay', 34.16, 135.04],
  ['hokkaido_se', 'tomakomai_appr', 42.01, 143.08],
  ['cook_inlet_s', 'cook_inlet', 59.79, -152.18],
  ['dixon_w', 'hecate_n', 54.24, -132.17],
  ['jdf_e', 'admiralty', 48.29, -123.15],
  ['manzanillo_appr', 'lazaro_appr', 18.31, -103.47],
  ['quetzal_appr', 'nicoya_appr', 11.46, -88.04],
  ['nicoya_appr', 'panama_pac', 7.58, -82.83],
  ['guayaquil_gulf', 'peru_n', -4.42, -81.36],
  ['callao_appr', 'peru_s', -14.42, -76.15],
  ['guafo', 'corcovado', -43.56, -74.06],
  ['staten_e', 'magellan_e', -53.84, -65.25],
  ['falklands_e', 'magellan_e', -52.54, -62.03],
  ['staten_e', 'beagle_e', -55.35, -64.69],
  ['bahia_blanca_appr', 'valdes_e', -40.94, -62.34],
  ['valdes_e', 'golfo_nuevo', -43.02, -63.95],
  ['santos_appr', 'ilha_grande_s', -23.85, -45.07],
  ['fortaleza_n', 'itaqui_appr', -2.50, -41.38],
  ['itaqui_appr', 'para_mouth', -0.90, -45.96],
  ['amapa', 'guiana', 5.2, -51.8],
  ['pr_n', 'mona', 18.55, -66.96],
  ['mona', 'caucedo_appr', 18.17, -68.70],
  ['windward_passage', 'jamaica_s', 18.61, -75.18],
  ['windward_passage', 'atlantic_bahamas', 22.08, -72.39],
  ['curacao_n', 'pto_cabello_appr', 11.62, -68.38],
  ['jamaica_s', 'yucatan', 19.23, -81.37],
  ['chesapeake_mouth', 'chesapeake_mid', 37.47, -76.08],
  ['nyc_appr', 'chesapeake_mouth', 38.66, -74.77],
  ['anticosti_s', 'gaspe_n', 49.24, -64.65],
  ['leeuwin', 'perth_appr', -33.74, 114.95],
  ['kangaroo_s', 'backstairs', -36.22, 138.11],
  ['kangaroo_s', 'otway_s', -37.96, 140.13],
  ['bass_strait', 'tasmania_ne', -40.40, 147.57],
  ['tasmania_ne', 'tasmania_se', -42.11, 148.39],
  ['newcastle_appr', 'port_macquarie_e', -32.24, 152.68],
  ['port_macquarie_e', 'brisbane_appr', -29.27, 154.71],
  ['gladstone_appr', 'hay_point_appr', -22.34, 150.69],
  ['cape_egmont_w', 'cook_strait', -40.33, 173.82],
  ['solomon_e', 'fiji_s', -16.54, 170.91],
  ['fiji_s', 'samoa_n', -15.91, -176.71],
  ['east_cape', 'fiji_s', -27.91, 179.94],
  ['rio_appr', 'sao_tome_e', -22.86, -41.71],
  ['sounion_e', 'sounion_e~kafireas_e', 37.73, 24.31],
  ['somalia_e~guardafui', 'guardafui', 9.63, 51.2],
  ['cape_egmont_w~cook_strait', 'cook_strait', -40.85, 174.21],
];
// Edges replaced by the routes above or by other lanes (gulf_aden–mombasa runs along the Somali coast now).
const DROPS = ['gulf_aden-mombasa_appr', 'rio_appr-abrolhos_e'];
VIAS.push(...DEEP_VIAS); // deep-water splits (server/lanes-deep.js), after the land splits they refine
for (const [a, b, lat, lon] of VIAS) {
  const id = `${a}~${b}`;
  WORLD_NODES.push(N(id, `Between ${a.replace(/_/g, ' ')} and ${b.replace(/_/g, ' ')}`, lat, lon, 'waypoint'));
  WORLD_EDGES.push(E(a, id), E(id, b));
}
const REPLACED = new Set([...VIAS.map(([a, b]) => `${a}-${b}`), ...DROPS]);
/** False for an edge that the world layer replaced (split at a waypoint or dropped). */
export function keepEdge(e) { return !REPLACED.has(`${e[0]}-${e[1]}`) && !REPLACED.has(`${e[1]}-${e[0]}`); }
/** Moves the lane nodes that sat in shallow water on the raster to deep water nearby (server/lanes-deep.js), in place. */
export function applyDeepMoves(nodes) {
  for (const n of nodes) { const m = DEEP_MOVES[n.id]; if (m && n.kind !== 'harbor' && n.kind !== 'river') { n.lat = m[0]; n.lon = m[1]; } }
  return nodes;
}
