#!/usr/bin/env node
// Saltline — generate shared/sail/polars.gen.js from the steady-state solver (docs/SAILING-CONTRACT.md §2.11).
// Uses the SAME aero/hydro modules as the game (shared/sail/vpp.js → aero.js, hydro.js, rigs.js).
// Grid: TWS 0, 2, …, 40 kn (+ 25 kn, a §2.12 check row) × TWA 0, 5, …, 180°. ≈ 15–25 min for all four classes.
//
//   node scripts/gen-polars.mjs                          all classes → shared/sail/polars.gen.js
//   node scripts/gen-polars.mjs --only sloop --part a.json   one class → a JSON part (run parts in parallel)
//   node scripts/gen-polars.mjs --merge a.json b.json …   merge parts → shared/sail/polars.gen.js
//   --out <file>  write somewhere else
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { RIGS, KN } from '../shared/sail/rigs.js';
import { polarPoint } from '../shared/sail/vpp.js';

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const opt = (k) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : null; };
const OUT = opt('--out') || join(here, '..', 'shared', 'sail', 'polars.gen.js');
export const TWS = [...Array.from({ length: 21 }, (_, i) => i * 2), 25].sort((a, b) => a - b);
export const TWA = Array.from({ length: 37 }, (_, i) => i * 5);

export function genClass(cls, log = () => {}) {
  const rig = RIGS[cls], kn = [], heel = [], lee = [], lv = [];
  for (const tws of TWS) {
    const t0 = Date.now();
    for (const twa of TWA) {
      if (tws === 0) { kn.push(0); heel.push(0); lee.push(0); lv.push(0); continue; }
      const r = polarPoint(cls, tws, twa);
      kn.push(Math.round((r.V / KN) * 100));
      heel.push(Math.round(Math.min(r.phi, rig.phiT) * 10));
      lee.push(Math.round(r.lam * 10));
      lv.push(r.lv);
    }
    log(`${cls} ${tws} kn ${((Date.now() - t0) / 1000).toFixed(1)} s`);
  }
  return { tws: TWS, twa: TWA, kn, heel, lee, lv };
}

function writeTable(polars) {
  const lines = ['// GENERATED by scripts/gen-polars.mjs — do not edit. Regenerate after any change to shared/sail/{rigs,aero,hydro,vpp}.js.',
    `// ${new Date().toISOString().slice(0, 10)}. Row-major [tws][twa]: kn = boat speed kn·100, heel = °·10 (capped at the rig's phiT), lee = leeway °·10, lv = plan level.`,
    'export const POLARS = {'];
  for (const [cls, p] of Object.entries(polars)) {
    lines.push(`  ${cls}: {`);
    for (const k of ['tws', 'twa', 'kn', 'heel', 'lee', 'lv']) lines.push(`    ${k}: [${p[k].join(',')}],`);
    lines.push('  },');
  }
  lines.push('};', '');
  writeFileSync(OUT, lines.join('\n'));
  console.log(`wrote ${OUT}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const log = (m) => console.log(m);
  if (args.includes('--merge')) {
    const files = args.slice(args.indexOf('--merge') + 1).filter((f) => !f.startsWith('--') && f !== OUT);
    const all = {};
    for (const f of files) Object.assign(all, JSON.parse(readFileSync(f, 'utf8')));
    const ordered = {}; for (const c of Object.keys(RIGS)) if (all[c]) ordered[c] = all[c];
    writeTable(ordered);
  } else {
    const only = opt('--only');
    const classes = only ? only.split(',') : Object.keys(RIGS);
    const res = {};
    for (const c of classes) res[c] = genClass(c, log);
    const part = opt('--part');
    if (part) { writeFileSync(part, JSON.stringify(res)); console.log(`wrote ${part}`); } else writeTable(res);
  }
}
